// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/api/httpbody.proto

#include "google/api/httpbody.pb.h"
#include "google/api/httpbody.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace google {
namespace api {

} // namespace google
} // namespace api

