// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kuksa/val/v2/types.proto

#include "kuksa/val/v2/types.pb.h"
#include "kuksa/val/v2/types.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace kuksa {
namespace val {
namespace v2 {

} // namespace kuksa
} // namespace val
} // namespace v2

