// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kuksa/val/v2/val.proto

#include "kuksa/val/v2/val.pb.h"
#include "kuksa/val/v2/val.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace kuksa {
namespace val {
namespace v2 {

class MockVALStub : public VAL::StubInterface {
 public:
  MOCK_METHOD3(GetValue, ::grpc::Status(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest& request, ::kuksa::val::v2::GetValueResponse* response));
  MOCK_METHOD3(AsyncGetValueRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::GetValueResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetValueRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::GetValueResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetValues, ::grpc::Status(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest& request, ::kuksa::val::v2::GetValuesResponse* response));
  MOCK_METHOD3(AsyncGetValuesRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::GetValuesResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetValuesRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::GetValuesResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(SubscribeRaw, ::grpc::ClientReaderInterface< ::kuksa::val::v2::SubscribeResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest& request));
  MOCK_METHOD4(AsyncSubscribeRaw, ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v2::SubscribeResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncSubscribeRaw, ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v2::SubscribeResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(SubscribeByIdRaw, ::grpc::ClientReaderInterface< ::kuksa::val::v2::SubscribeByIdResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest& request));
  MOCK_METHOD4(AsyncSubscribeByIdRaw, ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v2::SubscribeByIdResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncSubscribeByIdRaw, ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v2::SubscribeByIdResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(Actuate, ::grpc::Status(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest& request, ::kuksa::val::v2::ActuateResponse* response));
  MOCK_METHOD3(AsyncActuateRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::ActuateResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncActuateRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::ActuateResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(BatchActuate, ::grpc::Status(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest& request, ::kuksa::val::v2::BatchActuateResponse* response));
  MOCK_METHOD3(AsyncBatchActuateRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::BatchActuateResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncBatchActuateRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::BatchActuateResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(ListMetadata, ::grpc::Status(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest& request, ::kuksa::val::v2::ListMetadataResponse* response));
  MOCK_METHOD3(AsyncListMetadataRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::ListMetadataResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncListMetadataRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::ListMetadataResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PublishValue, ::grpc::Status(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest& request, ::kuksa::val::v2::PublishValueResponse* response));
  MOCK_METHOD3(AsyncPublishValueRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::PublishValueResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncPublishValueRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::PublishValueResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD1(OpenProviderStreamRaw, ::grpc::ClientReaderWriterInterface< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>*(::grpc::ClientContext* context));
  MOCK_METHOD3(AsyncOpenProviderStreamRaw, ::grpc::ClientAsyncReaderWriterInterface<::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>*(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD2(PrepareAsyncOpenProviderStreamRaw, ::grpc::ClientAsyncReaderWriterInterface<::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>*(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetServerInfo, ::grpc::Status(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest& request, ::kuksa::val::v2::GetServerInfoResponse* response));
  MOCK_METHOD3(AsyncGetServerInfoRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::GetServerInfoResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetServerInfoRaw, ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v2::GetServerInfoResponse>*(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq));
};

} // namespace kuksa
} // namespace val
} // namespace v2

