// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdv/databroker/v1/broker.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sdv_2fdatabroker_2fv1_2fbroker_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sdv_2fdatabroker_2fv1_2fbroker_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "sdv/databroker/v1/types.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sdv_2fdatabroker_2fv1_2fbroker_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
namespace sdv {
namespace databroker {
namespace v1 {
class GetDatapointsReply;
struct GetDatapointsReplyDefaultTypeInternal;
extern GetDatapointsReplyDefaultTypeInternal _GetDatapointsReply_default_instance_;
class GetDatapointsReply_DatapointsEntry_DoNotUse;
struct GetDatapointsReply_DatapointsEntry_DoNotUseDefaultTypeInternal;
extern GetDatapointsReply_DatapointsEntry_DoNotUseDefaultTypeInternal _GetDatapointsReply_DatapointsEntry_DoNotUse_default_instance_;
class GetDatapointsRequest;
struct GetDatapointsRequestDefaultTypeInternal;
extern GetDatapointsRequestDefaultTypeInternal _GetDatapointsRequest_default_instance_;
class GetMetadataReply;
struct GetMetadataReplyDefaultTypeInternal;
extern GetMetadataReplyDefaultTypeInternal _GetMetadataReply_default_instance_;
class GetMetadataRequest;
struct GetMetadataRequestDefaultTypeInternal;
extern GetMetadataRequestDefaultTypeInternal _GetMetadataRequest_default_instance_;
class SetDatapointsReply;
struct SetDatapointsReplyDefaultTypeInternal;
extern SetDatapointsReplyDefaultTypeInternal _SetDatapointsReply_default_instance_;
class SetDatapointsReply_ErrorsEntry_DoNotUse;
struct SetDatapointsReply_ErrorsEntry_DoNotUseDefaultTypeInternal;
extern SetDatapointsReply_ErrorsEntry_DoNotUseDefaultTypeInternal _SetDatapointsReply_ErrorsEntry_DoNotUse_default_instance_;
class SetDatapointsRequest;
struct SetDatapointsRequestDefaultTypeInternal;
extern SetDatapointsRequestDefaultTypeInternal _SetDatapointsRequest_default_instance_;
class SetDatapointsRequest_DatapointsEntry_DoNotUse;
struct SetDatapointsRequest_DatapointsEntry_DoNotUseDefaultTypeInternal;
extern SetDatapointsRequest_DatapointsEntry_DoNotUseDefaultTypeInternal _SetDatapointsRequest_DatapointsEntry_DoNotUse_default_instance_;
class SubscribeReply;
struct SubscribeReplyDefaultTypeInternal;
extern SubscribeReplyDefaultTypeInternal _SubscribeReply_default_instance_;
class SubscribeReply_FieldsEntry_DoNotUse;
struct SubscribeReply_FieldsEntry_DoNotUseDefaultTypeInternal;
extern SubscribeReply_FieldsEntry_DoNotUseDefaultTypeInternal _SubscribeReply_FieldsEntry_DoNotUse_default_instance_;
class SubscribeRequest;
struct SubscribeRequestDefaultTypeInternal;
extern SubscribeRequestDefaultTypeInternal _SubscribeRequest_default_instance_;
}  // namespace v1
}  // namespace databroker
}  // namespace sdv
PROTOBUF_NAMESPACE_OPEN
template<> ::sdv::databroker::v1::GetDatapointsReply* Arena::CreateMaybeMessage<::sdv::databroker::v1::GetDatapointsReply>(Arena*);
template<> ::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse* Arena::CreateMaybeMessage<::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse>(Arena*);
template<> ::sdv::databroker::v1::GetDatapointsRequest* Arena::CreateMaybeMessage<::sdv::databroker::v1::GetDatapointsRequest>(Arena*);
template<> ::sdv::databroker::v1::GetMetadataReply* Arena::CreateMaybeMessage<::sdv::databroker::v1::GetMetadataReply>(Arena*);
template<> ::sdv::databroker::v1::GetMetadataRequest* Arena::CreateMaybeMessage<::sdv::databroker::v1::GetMetadataRequest>(Arena*);
template<> ::sdv::databroker::v1::SetDatapointsReply* Arena::CreateMaybeMessage<::sdv::databroker::v1::SetDatapointsReply>(Arena*);
template<> ::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse* Arena::CreateMaybeMessage<::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse>(Arena*);
template<> ::sdv::databroker::v1::SetDatapointsRequest* Arena::CreateMaybeMessage<::sdv::databroker::v1::SetDatapointsRequest>(Arena*);
template<> ::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse* Arena::CreateMaybeMessage<::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse>(Arena*);
template<> ::sdv::databroker::v1::SubscribeReply* Arena::CreateMaybeMessage<::sdv::databroker::v1::SubscribeReply>(Arena*);
template<> ::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse* Arena::CreateMaybeMessage<::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse>(Arena*);
template<> ::sdv::databroker::v1::SubscribeRequest* Arena::CreateMaybeMessage<::sdv::databroker::v1::SubscribeRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sdv {
namespace databroker {
namespace v1 {

// ===================================================================

class GetDatapointsRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sdv.databroker.v1.GetDatapointsRequest) */ {
 public:
  inline GetDatapointsRequest() : GetDatapointsRequest(nullptr) {}
  ~GetDatapointsRequest() override;
  explicit PROTOBUF_CONSTEXPR GetDatapointsRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetDatapointsRequest(const GetDatapointsRequest& from);
  GetDatapointsRequest(GetDatapointsRequest&& from) noexcept
    : GetDatapointsRequest() {
    *this = ::std::move(from);
  }

  inline GetDatapointsRequest& operator=(const GetDatapointsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetDatapointsRequest& operator=(GetDatapointsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetDatapointsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetDatapointsRequest* internal_default_instance() {
    return reinterpret_cast<const GetDatapointsRequest*>(
               &_GetDatapointsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetDatapointsRequest& a, GetDatapointsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetDatapointsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetDatapointsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetDatapointsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetDatapointsRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetDatapointsRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetDatapointsRequest& from) {
    GetDatapointsRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDatapointsRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sdv.databroker.v1.GetDatapointsRequest";
  }
  protected:
  explicit GetDatapointsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDatapointsFieldNumber = 1,
  };
  // repeated string datapoints = 1;
  int datapoints_size() const;
  private:
  int _internal_datapoints_size() const;
  public:
  void clear_datapoints();
  const std::string& datapoints(int index) const;
  std::string* mutable_datapoints(int index);
  void set_datapoints(int index, const std::string& value);
  void set_datapoints(int index, std::string&& value);
  void set_datapoints(int index, const char* value);
  void set_datapoints(int index, const char* value, size_t size);
  std::string* add_datapoints();
  void add_datapoints(const std::string& value);
  void add_datapoints(std::string&& value);
  void add_datapoints(const char* value);
  void add_datapoints(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& datapoints() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_datapoints();
  private:
  const std::string& _internal_datapoints(int index) const;
  std::string* _internal_add_datapoints();
  public:

  // @@protoc_insertion_point(class_scope:sdv.databroker.v1.GetDatapointsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> datapoints_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};
// -------------------------------------------------------------------

class GetDatapointsReply_DatapointsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GetDatapointsReply_DatapointsEntry_DoNotUse, 
    std::string, ::sdv::databroker::v1::Datapoint,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GetDatapointsReply_DatapointsEntry_DoNotUse, 
    std::string, ::sdv::databroker::v1::Datapoint,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  GetDatapointsReply_DatapointsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR GetDatapointsReply_DatapointsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit GetDatapointsReply_DatapointsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const GetDatapointsReply_DatapointsEntry_DoNotUse& other);
  static const GetDatapointsReply_DatapointsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const GetDatapointsReply_DatapointsEntry_DoNotUse*>(&_GetDatapointsReply_DatapointsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "sdv.databroker.v1.GetDatapointsReply.DatapointsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};

// -------------------------------------------------------------------

class GetDatapointsReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sdv.databroker.v1.GetDatapointsReply) */ {
 public:
  inline GetDatapointsReply() : GetDatapointsReply(nullptr) {}
  ~GetDatapointsReply() override;
  explicit PROTOBUF_CONSTEXPR GetDatapointsReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetDatapointsReply(const GetDatapointsReply& from);
  GetDatapointsReply(GetDatapointsReply&& from) noexcept
    : GetDatapointsReply() {
    *this = ::std::move(from);
  }

  inline GetDatapointsReply& operator=(const GetDatapointsReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetDatapointsReply& operator=(GetDatapointsReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetDatapointsReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetDatapointsReply* internal_default_instance() {
    return reinterpret_cast<const GetDatapointsReply*>(
               &_GetDatapointsReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetDatapointsReply& a, GetDatapointsReply& b) {
    a.Swap(&b);
  }
  inline void Swap(GetDatapointsReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetDatapointsReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetDatapointsReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetDatapointsReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetDatapointsReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetDatapointsReply& from) {
    GetDatapointsReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDatapointsReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sdv.databroker.v1.GetDatapointsReply";
  }
  protected:
  explicit GetDatapointsReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kDatapointsFieldNumber = 1,
  };
  // map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
  int datapoints_size() const;
  private:
  int _internal_datapoints_size() const;
  public:
  void clear_datapoints();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
      _internal_datapoints() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
      _internal_mutable_datapoints();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
      datapoints() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
      mutable_datapoints();

  // @@protoc_insertion_point(class_scope:sdv.databroker.v1.GetDatapointsReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        GetDatapointsReply_DatapointsEntry_DoNotUse,
        std::string, ::sdv::databroker::v1::Datapoint,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> datapoints_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};
// -------------------------------------------------------------------

class SetDatapointsRequest_DatapointsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SetDatapointsRequest_DatapointsEntry_DoNotUse, 
    std::string, ::sdv::databroker::v1::Datapoint,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SetDatapointsRequest_DatapointsEntry_DoNotUse, 
    std::string, ::sdv::databroker::v1::Datapoint,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  SetDatapointsRequest_DatapointsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR SetDatapointsRequest_DatapointsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit SetDatapointsRequest_DatapointsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const SetDatapointsRequest_DatapointsEntry_DoNotUse& other);
  static const SetDatapointsRequest_DatapointsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SetDatapointsRequest_DatapointsEntry_DoNotUse*>(&_SetDatapointsRequest_DatapointsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "sdv.databroker.v1.SetDatapointsRequest.DatapointsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};

// -------------------------------------------------------------------

class SetDatapointsRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sdv.databroker.v1.SetDatapointsRequest) */ {
 public:
  inline SetDatapointsRequest() : SetDatapointsRequest(nullptr) {}
  ~SetDatapointsRequest() override;
  explicit PROTOBUF_CONSTEXPR SetDatapointsRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetDatapointsRequest(const SetDatapointsRequest& from);
  SetDatapointsRequest(SetDatapointsRequest&& from) noexcept
    : SetDatapointsRequest() {
    *this = ::std::move(from);
  }

  inline SetDatapointsRequest& operator=(const SetDatapointsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetDatapointsRequest& operator=(SetDatapointsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetDatapointsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetDatapointsRequest* internal_default_instance() {
    return reinterpret_cast<const SetDatapointsRequest*>(
               &_SetDatapointsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SetDatapointsRequest& a, SetDatapointsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SetDatapointsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetDatapointsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetDatapointsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetDatapointsRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetDatapointsRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SetDatapointsRequest& from) {
    SetDatapointsRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetDatapointsRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sdv.databroker.v1.SetDatapointsRequest";
  }
  protected:
  explicit SetDatapointsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kDatapointsFieldNumber = 1,
  };
  // map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
  int datapoints_size() const;
  private:
  int _internal_datapoints_size() const;
  public:
  void clear_datapoints();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
      _internal_datapoints() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
      _internal_mutable_datapoints();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
      datapoints() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
      mutable_datapoints();

  // @@protoc_insertion_point(class_scope:sdv.databroker.v1.SetDatapointsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        SetDatapointsRequest_DatapointsEntry_DoNotUse,
        std::string, ::sdv::databroker::v1::Datapoint,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> datapoints_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};
// -------------------------------------------------------------------

class SetDatapointsReply_ErrorsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SetDatapointsReply_ErrorsEntry_DoNotUse, 
    std::string, ::sdv::databroker::v1::DatapointError,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SetDatapointsReply_ErrorsEntry_DoNotUse, 
    std::string, ::sdv::databroker::v1::DatapointError,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM> SuperType;
  SetDatapointsReply_ErrorsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR SetDatapointsReply_ErrorsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit SetDatapointsReply_ErrorsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const SetDatapointsReply_ErrorsEntry_DoNotUse& other);
  static const SetDatapointsReply_ErrorsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SetDatapointsReply_ErrorsEntry_DoNotUse*>(&_SetDatapointsReply_ErrorsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "sdv.databroker.v1.SetDatapointsReply.ErrorsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};

// -------------------------------------------------------------------

class SetDatapointsReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sdv.databroker.v1.SetDatapointsReply) */ {
 public:
  inline SetDatapointsReply() : SetDatapointsReply(nullptr) {}
  ~SetDatapointsReply() override;
  explicit PROTOBUF_CONSTEXPR SetDatapointsReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetDatapointsReply(const SetDatapointsReply& from);
  SetDatapointsReply(SetDatapointsReply&& from) noexcept
    : SetDatapointsReply() {
    *this = ::std::move(from);
  }

  inline SetDatapointsReply& operator=(const SetDatapointsReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetDatapointsReply& operator=(SetDatapointsReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetDatapointsReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetDatapointsReply* internal_default_instance() {
    return reinterpret_cast<const SetDatapointsReply*>(
               &_SetDatapointsReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(SetDatapointsReply& a, SetDatapointsReply& b) {
    a.Swap(&b);
  }
  inline void Swap(SetDatapointsReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetDatapointsReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetDatapointsReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetDatapointsReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetDatapointsReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SetDatapointsReply& from) {
    SetDatapointsReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetDatapointsReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sdv.databroker.v1.SetDatapointsReply";
  }
  protected:
  explicit SetDatapointsReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kErrorsFieldNumber = 1,
  };
  // map<string, .sdv.databroker.v1.DatapointError> errors = 1;
  int errors_size() const;
  private:
  int _internal_errors_size() const;
  public:
  void clear_errors();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::DatapointError >&
      _internal_errors() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::DatapointError >*
      _internal_mutable_errors();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::DatapointError >&
      errors() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::DatapointError >*
      mutable_errors();

  // @@protoc_insertion_point(class_scope:sdv.databroker.v1.SetDatapointsReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        SetDatapointsReply_ErrorsEntry_DoNotUse,
        std::string, ::sdv::databroker::v1::DatapointError,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM> errors_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};
// -------------------------------------------------------------------

class SubscribeRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sdv.databroker.v1.SubscribeRequest) */ {
 public:
  inline SubscribeRequest() : SubscribeRequest(nullptr) {}
  ~SubscribeRequest() override;
  explicit PROTOBUF_CONSTEXPR SubscribeRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SubscribeRequest(const SubscribeRequest& from);
  SubscribeRequest(SubscribeRequest&& from) noexcept
    : SubscribeRequest() {
    *this = ::std::move(from);
  }

  inline SubscribeRequest& operator=(const SubscribeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubscribeRequest& operator=(SubscribeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SubscribeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SubscribeRequest* internal_default_instance() {
    return reinterpret_cast<const SubscribeRequest*>(
               &_SubscribeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(SubscribeRequest& a, SubscribeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SubscribeRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SubscribeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SubscribeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SubscribeRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SubscribeRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SubscribeRequest& from) {
    SubscribeRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SubscribeRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sdv.databroker.v1.SubscribeRequest";
  }
  protected:
  explicit SubscribeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQueryFieldNumber = 2,
  };
  // string query = 2;
  void clear_query();
  const std::string& query() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_query(ArgT0&& arg0, ArgT... args);
  std::string* mutable_query();
  PROTOBUF_NODISCARD std::string* release_query();
  void set_allocated_query(std::string* query);
  private:
  const std::string& _internal_query() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_query(const std::string& value);
  std::string* _internal_mutable_query();
  public:

  // @@protoc_insertion_point(class_scope:sdv.databroker.v1.SubscribeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr query_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};
// -------------------------------------------------------------------

class SubscribeReply_FieldsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SubscribeReply_FieldsEntry_DoNotUse, 
    std::string, ::sdv::databroker::v1::Datapoint,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SubscribeReply_FieldsEntry_DoNotUse, 
    std::string, ::sdv::databroker::v1::Datapoint,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  SubscribeReply_FieldsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR SubscribeReply_FieldsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit SubscribeReply_FieldsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const SubscribeReply_FieldsEntry_DoNotUse& other);
  static const SubscribeReply_FieldsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SubscribeReply_FieldsEntry_DoNotUse*>(&_SubscribeReply_FieldsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "sdv.databroker.v1.SubscribeReply.FieldsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};

// -------------------------------------------------------------------

class SubscribeReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sdv.databroker.v1.SubscribeReply) */ {
 public:
  inline SubscribeReply() : SubscribeReply(nullptr) {}
  ~SubscribeReply() override;
  explicit PROTOBUF_CONSTEXPR SubscribeReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SubscribeReply(const SubscribeReply& from);
  SubscribeReply(SubscribeReply&& from) noexcept
    : SubscribeReply() {
    *this = ::std::move(from);
  }

  inline SubscribeReply& operator=(const SubscribeReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubscribeReply& operator=(SubscribeReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SubscribeReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const SubscribeReply* internal_default_instance() {
    return reinterpret_cast<const SubscribeReply*>(
               &_SubscribeReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(SubscribeReply& a, SubscribeReply& b) {
    a.Swap(&b);
  }
  inline void Swap(SubscribeReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SubscribeReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SubscribeReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SubscribeReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SubscribeReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SubscribeReply& from) {
    SubscribeReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SubscribeReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sdv.databroker.v1.SubscribeReply";
  }
  protected:
  explicit SubscribeReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kFieldsFieldNumber = 1,
  };
  // map<string, .sdv.databroker.v1.Datapoint> fields = 1;
  int fields_size() const;
  private:
  int _internal_fields_size() const;
  public:
  void clear_fields();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
      _internal_fields() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
      _internal_mutable_fields();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
      fields() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
      mutable_fields();

  // @@protoc_insertion_point(class_scope:sdv.databroker.v1.SubscribeReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        SubscribeReply_FieldsEntry_DoNotUse,
        std::string, ::sdv::databroker::v1::Datapoint,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> fields_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};
// -------------------------------------------------------------------

class GetMetadataRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sdv.databroker.v1.GetMetadataRequest) */ {
 public:
  inline GetMetadataRequest() : GetMetadataRequest(nullptr) {}
  ~GetMetadataRequest() override;
  explicit PROTOBUF_CONSTEXPR GetMetadataRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetMetadataRequest(const GetMetadataRequest& from);
  GetMetadataRequest(GetMetadataRequest&& from) noexcept
    : GetMetadataRequest() {
    *this = ::std::move(from);
  }

  inline GetMetadataRequest& operator=(const GetMetadataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetMetadataRequest& operator=(GetMetadataRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetMetadataRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetMetadataRequest* internal_default_instance() {
    return reinterpret_cast<const GetMetadataRequest*>(
               &_GetMetadataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(GetMetadataRequest& a, GetMetadataRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetMetadataRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetMetadataRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetMetadataRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetMetadataRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetMetadataRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetMetadataRequest& from) {
    GetMetadataRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetMetadataRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sdv.databroker.v1.GetMetadataRequest";
  }
  protected:
  explicit GetMetadataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNamesFieldNumber = 1,
  };
  // repeated string names = 1;
  int names_size() const;
  private:
  int _internal_names_size() const;
  public:
  void clear_names();
  const std::string& names(int index) const;
  std::string* mutable_names(int index);
  void set_names(int index, const std::string& value);
  void set_names(int index, std::string&& value);
  void set_names(int index, const char* value);
  void set_names(int index, const char* value, size_t size);
  std::string* add_names();
  void add_names(const std::string& value);
  void add_names(std::string&& value);
  void add_names(const char* value);
  void add_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_names();
  private:
  const std::string& _internal_names(int index) const;
  std::string* _internal_add_names();
  public:

  // @@protoc_insertion_point(class_scope:sdv.databroker.v1.GetMetadataRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> names_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};
// -------------------------------------------------------------------

class GetMetadataReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sdv.databroker.v1.GetMetadataReply) */ {
 public:
  inline GetMetadataReply() : GetMetadataReply(nullptr) {}
  ~GetMetadataReply() override;
  explicit PROTOBUF_CONSTEXPR GetMetadataReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetMetadataReply(const GetMetadataReply& from);
  GetMetadataReply(GetMetadataReply&& from) noexcept
    : GetMetadataReply() {
    *this = ::std::move(from);
  }

  inline GetMetadataReply& operator=(const GetMetadataReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetMetadataReply& operator=(GetMetadataReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetMetadataReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetMetadataReply* internal_default_instance() {
    return reinterpret_cast<const GetMetadataReply*>(
               &_GetMetadataReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  friend void swap(GetMetadataReply& a, GetMetadataReply& b) {
    a.Swap(&b);
  }
  inline void Swap(GetMetadataReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetMetadataReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetMetadataReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetMetadataReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetMetadataReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetMetadataReply& from) {
    GetMetadataReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetMetadataReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sdv.databroker.v1.GetMetadataReply";
  }
  protected:
  explicit GetMetadataReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kListFieldNumber = 1,
  };
  // repeated .sdv.databroker.v1.Metadata list = 1;
  int list_size() const;
  private:
  int _internal_list_size() const;
  public:
  void clear_list();
  ::sdv::databroker::v1::Metadata* mutable_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sdv::databroker::v1::Metadata >*
      mutable_list();
  private:
  const ::sdv::databroker::v1::Metadata& _internal_list(int index) const;
  ::sdv::databroker::v1::Metadata* _internal_add_list();
  public:
  const ::sdv::databroker::v1::Metadata& list(int index) const;
  ::sdv::databroker::v1::Metadata* add_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sdv::databroker::v1::Metadata >&
      list() const;

  // @@protoc_insertion_point(class_scope:sdv.databroker.v1.GetMetadataReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sdv::databroker::v1::Metadata > list_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetDatapointsRequest

// repeated string datapoints = 1;
inline int GetDatapointsRequest::_internal_datapoints_size() const {
  return _impl_.datapoints_.size();
}
inline int GetDatapointsRequest::datapoints_size() const {
  return _internal_datapoints_size();
}
inline void GetDatapointsRequest::clear_datapoints() {
  _impl_.datapoints_.Clear();
}
inline std::string* GetDatapointsRequest::add_datapoints() {
  std::string* _s = _internal_add_datapoints();
  // @@protoc_insertion_point(field_add_mutable:sdv.databroker.v1.GetDatapointsRequest.datapoints)
  return _s;
}
inline const std::string& GetDatapointsRequest::_internal_datapoints(int index) const {
  return _impl_.datapoints_.Get(index);
}
inline const std::string& GetDatapointsRequest::datapoints(int index) const {
  // @@protoc_insertion_point(field_get:sdv.databroker.v1.GetDatapointsRequest.datapoints)
  return _internal_datapoints(index);
}
inline std::string* GetDatapointsRequest::mutable_datapoints(int index) {
  // @@protoc_insertion_point(field_mutable:sdv.databroker.v1.GetDatapointsRequest.datapoints)
  return _impl_.datapoints_.Mutable(index);
}
inline void GetDatapointsRequest::set_datapoints(int index, const std::string& value) {
  _impl_.datapoints_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:sdv.databroker.v1.GetDatapointsRequest.datapoints)
}
inline void GetDatapointsRequest::set_datapoints(int index, std::string&& value) {
  _impl_.datapoints_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:sdv.databroker.v1.GetDatapointsRequest.datapoints)
}
inline void GetDatapointsRequest::set_datapoints(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.datapoints_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sdv.databroker.v1.GetDatapointsRequest.datapoints)
}
inline void GetDatapointsRequest::set_datapoints(int index, const char* value, size_t size) {
  _impl_.datapoints_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sdv.databroker.v1.GetDatapointsRequest.datapoints)
}
inline std::string* GetDatapointsRequest::_internal_add_datapoints() {
  return _impl_.datapoints_.Add();
}
inline void GetDatapointsRequest::add_datapoints(const std::string& value) {
  _impl_.datapoints_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sdv.databroker.v1.GetDatapointsRequest.datapoints)
}
inline void GetDatapointsRequest::add_datapoints(std::string&& value) {
  _impl_.datapoints_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:sdv.databroker.v1.GetDatapointsRequest.datapoints)
}
inline void GetDatapointsRequest::add_datapoints(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.datapoints_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sdv.databroker.v1.GetDatapointsRequest.datapoints)
}
inline void GetDatapointsRequest::add_datapoints(const char* value, size_t size) {
  _impl_.datapoints_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sdv.databroker.v1.GetDatapointsRequest.datapoints)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetDatapointsRequest::datapoints() const {
  // @@protoc_insertion_point(field_list:sdv.databroker.v1.GetDatapointsRequest.datapoints)
  return _impl_.datapoints_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetDatapointsRequest::mutable_datapoints() {
  // @@protoc_insertion_point(field_mutable_list:sdv.databroker.v1.GetDatapointsRequest.datapoints)
  return &_impl_.datapoints_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GetDatapointsReply

// map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
inline int GetDatapointsReply::_internal_datapoints_size() const {
  return _impl_.datapoints_.size();
}
inline int GetDatapointsReply::datapoints_size() const {
  return _internal_datapoints_size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
GetDatapointsReply::_internal_datapoints() const {
  return _impl_.datapoints_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
GetDatapointsReply::datapoints() const {
  // @@protoc_insertion_point(field_map:sdv.databroker.v1.GetDatapointsReply.datapoints)
  return _internal_datapoints();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
GetDatapointsReply::_internal_mutable_datapoints() {
  return _impl_.datapoints_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
GetDatapointsReply::mutable_datapoints() {
  // @@protoc_insertion_point(field_mutable_map:sdv.databroker.v1.GetDatapointsReply.datapoints)
  return _internal_mutable_datapoints();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SetDatapointsRequest

// map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
inline int SetDatapointsRequest::_internal_datapoints_size() const {
  return _impl_.datapoints_.size();
}
inline int SetDatapointsRequest::datapoints_size() const {
  return _internal_datapoints_size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
SetDatapointsRequest::_internal_datapoints() const {
  return _impl_.datapoints_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
SetDatapointsRequest::datapoints() const {
  // @@protoc_insertion_point(field_map:sdv.databroker.v1.SetDatapointsRequest.datapoints)
  return _internal_datapoints();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
SetDatapointsRequest::_internal_mutable_datapoints() {
  return _impl_.datapoints_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
SetDatapointsRequest::mutable_datapoints() {
  // @@protoc_insertion_point(field_mutable_map:sdv.databroker.v1.SetDatapointsRequest.datapoints)
  return _internal_mutable_datapoints();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SetDatapointsReply

// map<string, .sdv.databroker.v1.DatapointError> errors = 1;
inline int SetDatapointsReply::_internal_errors_size() const {
  return _impl_.errors_.size();
}
inline int SetDatapointsReply::errors_size() const {
  return _internal_errors_size();
}
inline void SetDatapointsReply::clear_errors() {
  _impl_.errors_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::DatapointError >&
SetDatapointsReply::_internal_errors() const {
  return _impl_.errors_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::DatapointError >&
SetDatapointsReply::errors() const {
  // @@protoc_insertion_point(field_map:sdv.databroker.v1.SetDatapointsReply.errors)
  return _internal_errors();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::DatapointError >*
SetDatapointsReply::_internal_mutable_errors() {
  return _impl_.errors_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::DatapointError >*
SetDatapointsReply::mutable_errors() {
  // @@protoc_insertion_point(field_mutable_map:sdv.databroker.v1.SetDatapointsReply.errors)
  return _internal_mutable_errors();
}

// -------------------------------------------------------------------

// SubscribeRequest

// string query = 2;
inline void SubscribeRequest::clear_query() {
  _impl_.query_.ClearToEmpty();
}
inline const std::string& SubscribeRequest::query() const {
  // @@protoc_insertion_point(field_get:sdv.databroker.v1.SubscribeRequest.query)
  return _internal_query();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubscribeRequest::set_query(ArgT0&& arg0, ArgT... args) {
 
 _impl_.query_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sdv.databroker.v1.SubscribeRequest.query)
}
inline std::string* SubscribeRequest::mutable_query() {
  std::string* _s = _internal_mutable_query();
  // @@protoc_insertion_point(field_mutable:sdv.databroker.v1.SubscribeRequest.query)
  return _s;
}
inline const std::string& SubscribeRequest::_internal_query() const {
  return _impl_.query_.Get();
}
inline void SubscribeRequest::_internal_set_query(const std::string& value) {
  
  _impl_.query_.Set(value, GetArenaForAllocation());
}
inline std::string* SubscribeRequest::_internal_mutable_query() {
  
  return _impl_.query_.Mutable(GetArenaForAllocation());
}
inline std::string* SubscribeRequest::release_query() {
  // @@protoc_insertion_point(field_release:sdv.databroker.v1.SubscribeRequest.query)
  return _impl_.query_.Release();
}
inline void SubscribeRequest::set_allocated_query(std::string* query) {
  if (query != nullptr) {
    
  } else {
    
  }
  _impl_.query_.SetAllocated(query, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.query_.IsDefault()) {
    _impl_.query_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sdv.databroker.v1.SubscribeRequest.query)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SubscribeReply

// map<string, .sdv.databroker.v1.Datapoint> fields = 1;
inline int SubscribeReply::_internal_fields_size() const {
  return _impl_.fields_.size();
}
inline int SubscribeReply::fields_size() const {
  return _internal_fields_size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
SubscribeReply::_internal_fields() const {
  return _impl_.fields_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >&
SubscribeReply::fields() const {
  // @@protoc_insertion_point(field_map:sdv.databroker.v1.SubscribeReply.fields)
  return _internal_fields();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
SubscribeReply::_internal_mutable_fields() {
  return _impl_.fields_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >*
SubscribeReply::mutable_fields() {
  // @@protoc_insertion_point(field_mutable_map:sdv.databroker.v1.SubscribeReply.fields)
  return _internal_mutable_fields();
}

// -------------------------------------------------------------------

// GetMetadataRequest

// repeated string names = 1;
inline int GetMetadataRequest::_internal_names_size() const {
  return _impl_.names_.size();
}
inline int GetMetadataRequest::names_size() const {
  return _internal_names_size();
}
inline void GetMetadataRequest::clear_names() {
  _impl_.names_.Clear();
}
inline std::string* GetMetadataRequest::add_names() {
  std::string* _s = _internal_add_names();
  // @@protoc_insertion_point(field_add_mutable:sdv.databroker.v1.GetMetadataRequest.names)
  return _s;
}
inline const std::string& GetMetadataRequest::_internal_names(int index) const {
  return _impl_.names_.Get(index);
}
inline const std::string& GetMetadataRequest::names(int index) const {
  // @@protoc_insertion_point(field_get:sdv.databroker.v1.GetMetadataRequest.names)
  return _internal_names(index);
}
inline std::string* GetMetadataRequest::mutable_names(int index) {
  // @@protoc_insertion_point(field_mutable:sdv.databroker.v1.GetMetadataRequest.names)
  return _impl_.names_.Mutable(index);
}
inline void GetMetadataRequest::set_names(int index, const std::string& value) {
  _impl_.names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:sdv.databroker.v1.GetMetadataRequest.names)
}
inline void GetMetadataRequest::set_names(int index, std::string&& value) {
  _impl_.names_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:sdv.databroker.v1.GetMetadataRequest.names)
}
inline void GetMetadataRequest::set_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sdv.databroker.v1.GetMetadataRequest.names)
}
inline void GetMetadataRequest::set_names(int index, const char* value, size_t size) {
  _impl_.names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sdv.databroker.v1.GetMetadataRequest.names)
}
inline std::string* GetMetadataRequest::_internal_add_names() {
  return _impl_.names_.Add();
}
inline void GetMetadataRequest::add_names(const std::string& value) {
  _impl_.names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sdv.databroker.v1.GetMetadataRequest.names)
}
inline void GetMetadataRequest::add_names(std::string&& value) {
  _impl_.names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:sdv.databroker.v1.GetMetadataRequest.names)
}
inline void GetMetadataRequest::add_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sdv.databroker.v1.GetMetadataRequest.names)
}
inline void GetMetadataRequest::add_names(const char* value, size_t size) {
  _impl_.names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sdv.databroker.v1.GetMetadataRequest.names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetMetadataRequest::names() const {
  // @@protoc_insertion_point(field_list:sdv.databroker.v1.GetMetadataRequest.names)
  return _impl_.names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetMetadataRequest::mutable_names() {
  // @@protoc_insertion_point(field_mutable_list:sdv.databroker.v1.GetMetadataRequest.names)
  return &_impl_.names_;
}

// -------------------------------------------------------------------

// GetMetadataReply

// repeated .sdv.databroker.v1.Metadata list = 1;
inline int GetMetadataReply::_internal_list_size() const {
  return _impl_.list_.size();
}
inline int GetMetadataReply::list_size() const {
  return _internal_list_size();
}
inline ::sdv::databroker::v1::Metadata* GetMetadataReply::mutable_list(int index) {
  // @@protoc_insertion_point(field_mutable:sdv.databroker.v1.GetMetadataReply.list)
  return _impl_.list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sdv::databroker::v1::Metadata >*
GetMetadataReply::mutable_list() {
  // @@protoc_insertion_point(field_mutable_list:sdv.databroker.v1.GetMetadataReply.list)
  return &_impl_.list_;
}
inline const ::sdv::databroker::v1::Metadata& GetMetadataReply::_internal_list(int index) const {
  return _impl_.list_.Get(index);
}
inline const ::sdv::databroker::v1::Metadata& GetMetadataReply::list(int index) const {
  // @@protoc_insertion_point(field_get:sdv.databroker.v1.GetMetadataReply.list)
  return _internal_list(index);
}
inline ::sdv::databroker::v1::Metadata* GetMetadataReply::_internal_add_list() {
  return _impl_.list_.Add();
}
inline ::sdv::databroker::v1::Metadata* GetMetadataReply::add_list() {
  ::sdv::databroker::v1::Metadata* _add = _internal_add_list();
  // @@protoc_insertion_point(field_add:sdv.databroker.v1.GetMetadataReply.list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sdv::databroker::v1::Metadata >&
GetMetadataReply::list() const {
  // @@protoc_insertion_point(field_list:sdv.databroker.v1.GetMetadataReply.list)
  return _impl_.list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace databroker
}  // namespace sdv

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sdv_2fdatabroker_2fv1_2fbroker_2eproto
