// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sdv/databroker/v1/broker.proto
// Original file comments:
// *******************************************************************************
// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License 2.0 which is available at
// http://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// ******************************************************************************
//
#ifndef GRPC_sdv_2fdatabroker_2fv1_2fbroker_2eproto__INCLUDED
#define GRPC_sdv_2fdatabroker_2fv1_2fbroker_2eproto__INCLUDED

#include "sdv/databroker/v1/broker.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace sdv {
namespace databroker {
namespace v1 {

class Broker final {
 public:
  static constexpr char const* service_full_name() {
    return "sdv.databroker.v1.Broker";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Request a set of datapoints (values)
    //
    // Returns a list of requested data points.
    //
    // InvalidArgument is returned if the request is malformed.
    virtual ::grpc::Status GetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::sdv::databroker::v1::GetDatapointsReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetDatapointsReply>> AsyncGetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetDatapointsReply>>(AsyncGetDatapointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetDatapointsReply>> PrepareAsyncGetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetDatapointsReply>>(PrepareAsyncGetDatapointsRaw(context, request, cq));
    }
    // Set a datapoint (values)
    virtual ::grpc::Status SetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::sdv::databroker::v1::SetDatapointsReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::SetDatapointsReply>> AsyncSetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::SetDatapointsReply>>(AsyncSetDatapointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::SetDatapointsReply>> PrepareAsyncSetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::SetDatapointsReply>>(PrepareAsyncSetDatapointsRaw(context, request, cq));
    }
    // Subscribe to a set of data points or conditional expressions
    // using the Data Broker Query Syntax (described in QUERY.md)
    //
    // Returns a stream of replies.
    //
    // InvalidArgument is returned if the request is malformed.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::sdv::databroker::v1::SubscribeReply>> Subscribe(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::sdv::databroker::v1::SubscribeReply>>(SubscribeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::sdv::databroker::v1::SubscribeReply>> AsyncSubscribe(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::sdv::databroker::v1::SubscribeReply>>(AsyncSubscribeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::sdv::databroker::v1::SubscribeReply>> PrepareAsyncSubscribe(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::sdv::databroker::v1::SubscribeReply>>(PrepareAsyncSubscribeRaw(context, request, cq));
    }
    // Request the metadata of a set of datapoints
    //
    // Returns metadata of the requested data points that exist.
    virtual ::grpc::Status GetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::sdv::databroker::v1::GetMetadataReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetMetadataReply>> AsyncGetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetMetadataReply>>(AsyncGetMetadataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetMetadataReply>> PrepareAsyncGetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetMetadataReply>>(PrepareAsyncGetMetadataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Request a set of datapoints (values)
      //
      // Returns a list of requested data points.
      //
      // InvalidArgument is returned if the request is malformed.
      virtual void GetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest* request, ::sdv::databroker::v1::GetDatapointsReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest* request, ::sdv::databroker::v1::GetDatapointsReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Set a datapoint (values)
      virtual void SetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest* request, ::sdv::databroker::v1::SetDatapointsReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest* request, ::sdv::databroker::v1::SetDatapointsReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Subscribe to a set of data points or conditional expressions
      // using the Data Broker Query Syntax (described in QUERY.md)
      //
      // Returns a stream of replies.
      //
      // InvalidArgument is returned if the request is malformed.
      virtual void Subscribe(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest* request, ::grpc::ClientReadReactor< ::sdv::databroker::v1::SubscribeReply>* reactor) = 0;
      // Request the metadata of a set of datapoints
      //
      // Returns metadata of the requested data points that exist.
      virtual void GetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest* request, ::sdv::databroker::v1::GetMetadataReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest* request, ::sdv::databroker::v1::GetMetadataReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetDatapointsReply>* AsyncGetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetDatapointsReply>* PrepareAsyncGetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::SetDatapointsReply>* AsyncSetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::SetDatapointsReply>* PrepareAsyncSetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::sdv::databroker::v1::SubscribeReply>* SubscribeRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::sdv::databroker::v1::SubscribeReply>* AsyncSubscribeRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::sdv::databroker::v1::SubscribeReply>* PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetMetadataReply>* AsyncGetMetadataRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetMetadataReply>* PrepareAsyncGetMetadataRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::sdv::databroker::v1::GetDatapointsReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetDatapointsReply>> AsyncGetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetDatapointsReply>>(AsyncGetDatapointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetDatapointsReply>> PrepareAsyncGetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetDatapointsReply>>(PrepareAsyncGetDatapointsRaw(context, request, cq));
    }
    ::grpc::Status SetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::sdv::databroker::v1::SetDatapointsReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::SetDatapointsReply>> AsyncSetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::SetDatapointsReply>>(AsyncSetDatapointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::SetDatapointsReply>> PrepareAsyncSetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::SetDatapointsReply>>(PrepareAsyncSetDatapointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::sdv::databroker::v1::SubscribeReply>> Subscribe(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::sdv::databroker::v1::SubscribeReply>>(SubscribeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::sdv::databroker::v1::SubscribeReply>> AsyncSubscribe(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::sdv::databroker::v1::SubscribeReply>>(AsyncSubscribeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::sdv::databroker::v1::SubscribeReply>> PrepareAsyncSubscribe(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::sdv::databroker::v1::SubscribeReply>>(PrepareAsyncSubscribeRaw(context, request, cq));
    }
    ::grpc::Status GetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::sdv::databroker::v1::GetMetadataReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetMetadataReply>> AsyncGetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetMetadataReply>>(AsyncGetMetadataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetMetadataReply>> PrepareAsyncGetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetMetadataReply>>(PrepareAsyncGetMetadataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest* request, ::sdv::databroker::v1::GetDatapointsReply* response, std::function<void(::grpc::Status)>) override;
      void GetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest* request, ::sdv::databroker::v1::GetDatapointsReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest* request, ::sdv::databroker::v1::SetDatapointsReply* response, std::function<void(::grpc::Status)>) override;
      void SetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest* request, ::sdv::databroker::v1::SetDatapointsReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Subscribe(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest* request, ::grpc::ClientReadReactor< ::sdv::databroker::v1::SubscribeReply>* reactor) override;
      void GetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest* request, ::sdv::databroker::v1::GetMetadataReply* response, std::function<void(::grpc::Status)>) override;
      void GetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest* request, ::sdv::databroker::v1::GetMetadataReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetDatapointsReply>* AsyncGetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetDatapointsReply>* PrepareAsyncGetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::SetDatapointsReply>* AsyncSetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::SetDatapointsReply>* PrepareAsyncSetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::sdv::databroker::v1::SubscribeReply>* SubscribeRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request) override;
    ::grpc::ClientAsyncReader< ::sdv::databroker::v1::SubscribeReply>* AsyncSubscribeRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::sdv::databroker::v1::SubscribeReply>* PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetMetadataReply>* AsyncGetMetadataRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetMetadataReply>* PrepareAsyncGetMetadataRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetDatapoints_;
    const ::grpc::internal::RpcMethod rpcmethod_SetDatapoints_;
    const ::grpc::internal::RpcMethod rpcmethod_Subscribe_;
    const ::grpc::internal::RpcMethod rpcmethod_GetMetadata_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Request a set of datapoints (values)
    //
    // Returns a list of requested data points.
    //
    // InvalidArgument is returned if the request is malformed.
    virtual ::grpc::Status GetDatapoints(::grpc::ServerContext* context, const ::sdv::databroker::v1::GetDatapointsRequest* request, ::sdv::databroker::v1::GetDatapointsReply* response);
    // Set a datapoint (values)
    virtual ::grpc::Status SetDatapoints(::grpc::ServerContext* context, const ::sdv::databroker::v1::SetDatapointsRequest* request, ::sdv::databroker::v1::SetDatapointsReply* response);
    // Subscribe to a set of data points or conditional expressions
    // using the Data Broker Query Syntax (described in QUERY.md)
    //
    // Returns a stream of replies.
    //
    // InvalidArgument is returned if the request is malformed.
    virtual ::grpc::Status Subscribe(::grpc::ServerContext* context, const ::sdv::databroker::v1::SubscribeRequest* request, ::grpc::ServerWriter< ::sdv::databroker::v1::SubscribeReply>* writer);
    // Request the metadata of a set of datapoints
    //
    // Returns metadata of the requested data points that exist.
    virtual ::grpc::Status GetMetadata(::grpc::ServerContext* context, const ::sdv::databroker::v1::GetMetadataRequest* request, ::sdv::databroker::v1::GetMetadataReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDatapoints() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetDatapointsRequest* /*request*/, ::sdv::databroker::v1::GetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDatapoints(::grpc::ServerContext* context, ::sdv::databroker::v1::GetDatapointsRequest* request, ::grpc::ServerAsyncResponseWriter< ::sdv::databroker::v1::GetDatapointsReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetDatapoints() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SetDatapointsRequest* /*request*/, ::sdv::databroker::v1::SetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetDatapoints(::grpc::ServerContext* context, ::sdv::databroker::v1::SetDatapointsRequest* request, ::grpc::ServerAsyncResponseWriter< ::sdv::databroker::v1::SetDatapointsReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Subscribe() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::sdv::databroker::v1::SubscribeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribe(::grpc::ServerContext* context, ::sdv::databroker::v1::SubscribeRequest* request, ::grpc::ServerAsyncWriter< ::sdv::databroker::v1::SubscribeReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMetadata : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMetadata() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetMetadata() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetadata(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetMetadataRequest* /*request*/, ::sdv::databroker::v1::GetMetadataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMetadata(::grpc::ServerContext* context, ::sdv::databroker::v1::GetMetadataRequest* request, ::grpc::ServerAsyncResponseWriter< ::sdv::databroker::v1::GetMetadataReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetDatapoints<WithAsyncMethod_SetDatapoints<WithAsyncMethod_Subscribe<WithAsyncMethod_GetMetadata<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetDatapoints() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sdv::databroker::v1::GetDatapointsRequest, ::sdv::databroker::v1::GetDatapointsReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sdv::databroker::v1::GetDatapointsRequest* request, ::sdv::databroker::v1::GetDatapointsReply* response) { return this->GetDatapoints(context, request, response); }));}
    void SetMessageAllocatorFor_GetDatapoints(
        ::grpc::MessageAllocator< ::sdv::databroker::v1::GetDatapointsRequest, ::sdv::databroker::v1::GetDatapointsReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sdv::databroker::v1::GetDatapointsRequest, ::sdv::databroker::v1::GetDatapointsReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetDatapointsRequest* /*request*/, ::sdv::databroker::v1::GetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDatapoints(
      ::grpc::CallbackServerContext* /*context*/, const ::sdv::databroker::v1::GetDatapointsRequest* /*request*/, ::sdv::databroker::v1::GetDatapointsReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetDatapoints() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::sdv::databroker::v1::SetDatapointsRequest, ::sdv::databroker::v1::SetDatapointsReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sdv::databroker::v1::SetDatapointsRequest* request, ::sdv::databroker::v1::SetDatapointsReply* response) { return this->SetDatapoints(context, request, response); }));}
    void SetMessageAllocatorFor_SetDatapoints(
        ::grpc::MessageAllocator< ::sdv::databroker::v1::SetDatapointsRequest, ::sdv::databroker::v1::SetDatapointsReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sdv::databroker::v1::SetDatapointsRequest, ::sdv::databroker::v1::SetDatapointsReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SetDatapointsRequest* /*request*/, ::sdv::databroker::v1::SetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetDatapoints(
      ::grpc::CallbackServerContext* /*context*/, const ::sdv::databroker::v1::SetDatapointsRequest* /*request*/, ::sdv::databroker::v1::SetDatapointsReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Subscribe() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::sdv::databroker::v1::SubscribeRequest, ::sdv::databroker::v1::SubscribeReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sdv::databroker::v1::SubscribeRequest* request) { return this->Subscribe(context, request); }));
    }
    ~WithCallbackMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::sdv::databroker::v1::SubscribeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::sdv::databroker::v1::SubscribeReply>* Subscribe(
      ::grpc::CallbackServerContext* /*context*/, const ::sdv::databroker::v1::SubscribeRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetMetadata : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetMetadata() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::sdv::databroker::v1::GetMetadataRequest, ::sdv::databroker::v1::GetMetadataReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sdv::databroker::v1::GetMetadataRequest* request, ::sdv::databroker::v1::GetMetadataReply* response) { return this->GetMetadata(context, request, response); }));}
    void SetMessageAllocatorFor_GetMetadata(
        ::grpc::MessageAllocator< ::sdv::databroker::v1::GetMetadataRequest, ::sdv::databroker::v1::GetMetadataReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sdv::databroker::v1::GetMetadataRequest, ::sdv::databroker::v1::GetMetadataReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetMetadata() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetadata(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetMetadataRequest* /*request*/, ::sdv::databroker::v1::GetMetadataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMetadata(
      ::grpc::CallbackServerContext* /*context*/, const ::sdv::databroker::v1::GetMetadataRequest* /*request*/, ::sdv::databroker::v1::GetMetadataReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetDatapoints<WithCallbackMethod_SetDatapoints<WithCallbackMethod_Subscribe<WithCallbackMethod_GetMetadata<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDatapoints() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetDatapointsRequest* /*request*/, ::sdv::databroker::v1::GetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetDatapoints() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SetDatapointsRequest* /*request*/, ::sdv::databroker::v1::SetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Subscribe() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::sdv::databroker::v1::SubscribeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetMetadata : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMetadata() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetMetadata() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetadata(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetMetadataRequest* /*request*/, ::sdv::databroker::v1::GetMetadataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDatapoints() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetDatapointsRequest* /*request*/, ::sdv::databroker::v1::GetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDatapoints(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetDatapoints() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SetDatapointsRequest* /*request*/, ::sdv::databroker::v1::SetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetDatapoints(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Subscribe() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::sdv::databroker::v1::SubscribeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribe(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMetadata : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMetadata() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetMetadata() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetadata(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetMetadataRequest* /*request*/, ::sdv::databroker::v1::GetMetadataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMetadata(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetDatapoints() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDatapoints(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetDatapointsRequest* /*request*/, ::sdv::databroker::v1::GetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDatapoints(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetDatapoints() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetDatapoints(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SetDatapointsRequest* /*request*/, ::sdv::databroker::v1::SetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetDatapoints(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Subscribe() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Subscribe(context, request); }));
    }
    ~WithRawCallbackMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::sdv::databroker::v1::SubscribeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Subscribe(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetMetadata : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetMetadata() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMetadata(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetMetadata() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetadata(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetMetadataRequest* /*request*/, ::sdv::databroker::v1::GetMetadataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMetadata(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDatapoints() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sdv::databroker::v1::GetDatapointsRequest, ::sdv::databroker::v1::GetDatapointsReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sdv::databroker::v1::GetDatapointsRequest, ::sdv::databroker::v1::GetDatapointsReply>* streamer) {
                       return this->StreamedGetDatapoints(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetDatapointsRequest* /*request*/, ::sdv::databroker::v1::GetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDatapoints(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sdv::databroker::v1::GetDatapointsRequest,::sdv::databroker::v1::GetDatapointsReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetDatapoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetDatapoints() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sdv::databroker::v1::SetDatapointsRequest, ::sdv::databroker::v1::SetDatapointsReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sdv::databroker::v1::SetDatapointsRequest, ::sdv::databroker::v1::SetDatapointsReply>* streamer) {
                       return this->StreamedSetDatapoints(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetDatapoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetDatapoints(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SetDatapointsRequest* /*request*/, ::sdv::databroker::v1::SetDatapointsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetDatapoints(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sdv::databroker::v1::SetDatapointsRequest,::sdv::databroker::v1::SetDatapointsReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMetadata : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMetadata() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sdv::databroker::v1::GetMetadataRequest, ::sdv::databroker::v1::GetMetadataReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sdv::databroker::v1::GetMetadataRequest, ::sdv::databroker::v1::GetMetadataReply>* streamer) {
                       return this->StreamedGetMetadata(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMetadata() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMetadata(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::GetMetadataRequest* /*request*/, ::sdv::databroker::v1::GetMetadataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMetadata(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sdv::databroker::v1::GetMetadataRequest,::sdv::databroker::v1::GetMetadataReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetDatapoints<WithStreamedUnaryMethod_SetDatapoints<WithStreamedUnaryMethod_GetMetadata<Service > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Subscribe() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::sdv::databroker::v1::SubscribeRequest, ::sdv::databroker::v1::SubscribeReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::sdv::databroker::v1::SubscribeRequest, ::sdv::databroker::v1::SubscribeReply>* streamer) {
                       return this->StreamedSubscribe(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::sdv::databroker::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::sdv::databroker::v1::SubscribeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSubscribe(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::sdv::databroker::v1::SubscribeRequest,::sdv::databroker::v1::SubscribeReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Subscribe<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetDatapoints<WithStreamedUnaryMethod_SetDatapoints<WithSplitStreamingMethod_Subscribe<WithStreamedUnaryMethod_GetMetadata<Service > > > > StreamedService;
};

}  // namespace v1
}  // namespace databroker
}  // namespace sdv


#endif  // GRPC_sdv_2fdatabroker_2fv1_2fbroker_2eproto__INCLUDED
