// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sdv/databroker/v1/broker.proto

#include "sdv/databroker/v1/broker.pb.h"
#include "sdv/databroker/v1/broker.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace sdv {
namespace databroker {
namespace v1 {

class MockBrokerStub : public Broker::StubInterface {
 public:
  MOCK_METHOD3(GetDatapoints, ::grpc::Status(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::sdv::databroker::v1::GetDatapointsReply* response));
  MOCK_METHOD3(AsyncGetDatapointsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetDatapointsReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetDatapointsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetDatapointsReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(SetDatapoints, ::grpc::Status(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::sdv::databroker::v1::SetDatapointsReply* response));
  MOCK_METHOD3(AsyncSetDatapointsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::SetDatapointsReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncSetDatapointsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::SetDatapointsReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(SubscribeRaw, ::grpc::ClientReaderInterface< ::sdv::databroker::v1::SubscribeReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request));
  MOCK_METHOD4(AsyncSubscribeRaw, ::grpc::ClientAsyncReaderInterface< ::sdv::databroker::v1::SubscribeReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncSubscribeRaw, ::grpc::ClientAsyncReaderInterface< ::sdv::databroker::v1::SubscribeReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetMetadata, ::grpc::Status(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::sdv::databroker::v1::GetMetadataReply* response));
  MOCK_METHOD3(AsyncGetMetadataRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetMetadataReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetMetadataRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::GetMetadataReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq));
};

} // namespace sdv
} // namespace databroker
} // namespace v1

