// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sdv/databroker/v1/broker.proto

#include "sdv/databroker/v1/broker.pb.h"
#include "sdv/databroker/v1/broker.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sdv {
namespace databroker {
namespace v1 {

static const char* Broker_method_names[] = {
  "/sdv.databroker.v1.Broker/GetDatapoints",
  "/sdv.databroker.v1.Broker/SetDatapoints",
  "/sdv.databroker.v1.Broker/Subscribe",
  "/sdv.databroker.v1.Broker/GetMetadata",
};

std::unique_ptr< Broker::Stub> Broker::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Broker::Stub> stub(new Broker::Stub(channel, options));
  return stub;
}

Broker::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetDatapoints_(Broker_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetDatapoints_(Broker_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Subscribe_(Broker_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetMetadata_(Broker_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Broker::Stub::GetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::sdv::databroker::v1::GetDatapointsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sdv::databroker::v1::GetDatapointsRequest, ::sdv::databroker::v1::GetDatapointsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDatapoints_, context, request, response);
}

void Broker::Stub::async::GetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest* request, ::sdv::databroker::v1::GetDatapointsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sdv::databroker::v1::GetDatapointsRequest, ::sdv::databroker::v1::GetDatapointsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDatapoints_, context, request, response, std::move(f));
}

void Broker::Stub::async::GetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest* request, ::sdv::databroker::v1::GetDatapointsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDatapoints_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetDatapointsReply>* Broker::Stub::PrepareAsyncGetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sdv::databroker::v1::GetDatapointsReply, ::sdv::databroker::v1::GetDatapointsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDatapoints_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetDatapointsReply>* Broker::Stub::AsyncGetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDatapointsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Broker::Stub::SetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::sdv::databroker::v1::SetDatapointsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sdv::databroker::v1::SetDatapointsRequest, ::sdv::databroker::v1::SetDatapointsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDatapoints_, context, request, response);
}

void Broker::Stub::async::SetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest* request, ::sdv::databroker::v1::SetDatapointsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sdv::databroker::v1::SetDatapointsRequest, ::sdv::databroker::v1::SetDatapointsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDatapoints_, context, request, response, std::move(f));
}

void Broker::Stub::async::SetDatapoints(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest* request, ::sdv::databroker::v1::SetDatapointsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDatapoints_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::SetDatapointsReply>* Broker::Stub::PrepareAsyncSetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sdv::databroker::v1::SetDatapointsReply, ::sdv::databroker::v1::SetDatapointsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDatapoints_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::SetDatapointsReply>* Broker::Stub::AsyncSetDatapointsRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SetDatapointsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDatapointsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::sdv::databroker::v1::SubscribeReply>* Broker::Stub::SubscribeRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::sdv::databroker::v1::SubscribeReply>::Create(channel_.get(), rpcmethod_Subscribe_, context, request);
}

void Broker::Stub::async::Subscribe(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest* request, ::grpc::ClientReadReactor< ::sdv::databroker::v1::SubscribeReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::sdv::databroker::v1::SubscribeReply>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::sdv::databroker::v1::SubscribeReply>* Broker::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::sdv::databroker::v1::SubscribeReply>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::sdv::databroker::v1::SubscribeReply>* Broker::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::sdv::databroker::v1::SubscribeReply>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false, nullptr);
}

::grpc::Status Broker::Stub::GetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::sdv::databroker::v1::GetMetadataReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sdv::databroker::v1::GetMetadataRequest, ::sdv::databroker::v1::GetMetadataReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMetadata_, context, request, response);
}

void Broker::Stub::async::GetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest* request, ::sdv::databroker::v1::GetMetadataReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sdv::databroker::v1::GetMetadataRequest, ::sdv::databroker::v1::GetMetadataReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetadata_, context, request, response, std::move(f));
}

void Broker::Stub::async::GetMetadata(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest* request, ::sdv::databroker::v1::GetMetadataReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetadata_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetMetadataReply>* Broker::Stub::PrepareAsyncGetMetadataRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sdv::databroker::v1::GetMetadataReply, ::sdv::databroker::v1::GetMetadataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMetadata_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sdv::databroker::v1::GetMetadataReply>* Broker::Stub::AsyncGetMetadataRaw(::grpc::ClientContext* context, const ::sdv::databroker::v1::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMetadataRaw(context, request, cq);
  result->StartCall();
  return result;
}

Broker::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Broker_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Broker::Service, ::sdv::databroker::v1::GetDatapointsRequest, ::sdv::databroker::v1::GetDatapointsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Broker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sdv::databroker::v1::GetDatapointsRequest* req,
             ::sdv::databroker::v1::GetDatapointsReply* resp) {
               return service->GetDatapoints(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Broker_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Broker::Service, ::sdv::databroker::v1::SetDatapointsRequest, ::sdv::databroker::v1::SetDatapointsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Broker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sdv::databroker::v1::SetDatapointsRequest* req,
             ::sdv::databroker::v1::SetDatapointsReply* resp) {
               return service->SetDatapoints(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Broker_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Broker::Service, ::sdv::databroker::v1::SubscribeRequest, ::sdv::databroker::v1::SubscribeReply>(
          [](Broker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sdv::databroker::v1::SubscribeRequest* req,
             ::grpc::ServerWriter<::sdv::databroker::v1::SubscribeReply>* writer) {
               return service->Subscribe(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Broker_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Broker::Service, ::sdv::databroker::v1::GetMetadataRequest, ::sdv::databroker::v1::GetMetadataReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Broker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sdv::databroker::v1::GetMetadataRequest* req,
             ::sdv::databroker::v1::GetMetadataReply* resp) {
               return service->GetMetadata(ctx, req, resp);
             }, this)));
}

Broker::Service::~Service() {
}

::grpc::Status Broker::Service::GetDatapoints(::grpc::ServerContext* context, const ::sdv::databroker::v1::GetDatapointsRequest* request, ::sdv::databroker::v1::GetDatapointsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Broker::Service::SetDatapoints(::grpc::ServerContext* context, const ::sdv::databroker::v1::SetDatapointsRequest* request, ::sdv::databroker::v1::SetDatapointsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Broker::Service::Subscribe(::grpc::ServerContext* context, const ::sdv::databroker::v1::SubscribeRequest* request, ::grpc::ServerWriter< ::sdv::databroker::v1::SubscribeReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Broker::Service::GetMetadata(::grpc::ServerContext* context, const ::sdv::databroker::v1::GetMetadataRequest* request, ::sdv::databroker::v1::GetMetadataReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sdv
}  // namespace databroker
}  // namespace v1

