// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdv/databroker/v1/broker.proto

#include "sdv/databroker/v1/broker.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sdv {
namespace databroker {
namespace v1 {
PROTOBUF_CONSTEXPR GetDatapointsRequest::GetDatapointsRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.datapoints_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetDatapointsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetDatapointsRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetDatapointsRequestDefaultTypeInternal() {}
  union {
    GetDatapointsRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetDatapointsRequestDefaultTypeInternal _GetDatapointsRequest_default_instance_;
PROTOBUF_CONSTEXPR GetDatapointsReply_DatapointsEntry_DoNotUse::GetDatapointsReply_DatapointsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct GetDatapointsReply_DatapointsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetDatapointsReply_DatapointsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetDatapointsReply_DatapointsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    GetDatapointsReply_DatapointsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetDatapointsReply_DatapointsEntry_DoNotUseDefaultTypeInternal _GetDatapointsReply_DatapointsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR GetDatapointsReply::GetDatapointsReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.datapoints_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetDatapointsReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetDatapointsReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetDatapointsReplyDefaultTypeInternal() {}
  union {
    GetDatapointsReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetDatapointsReplyDefaultTypeInternal _GetDatapointsReply_default_instance_;
PROTOBUF_CONSTEXPR SetDatapointsRequest_DatapointsEntry_DoNotUse::SetDatapointsRequest_DatapointsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct SetDatapointsRequest_DatapointsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetDatapointsRequest_DatapointsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetDatapointsRequest_DatapointsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    SetDatapointsRequest_DatapointsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetDatapointsRequest_DatapointsEntry_DoNotUseDefaultTypeInternal _SetDatapointsRequest_DatapointsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR SetDatapointsRequest::SetDatapointsRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.datapoints_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SetDatapointsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetDatapointsRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetDatapointsRequestDefaultTypeInternal() {}
  union {
    SetDatapointsRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetDatapointsRequestDefaultTypeInternal _SetDatapointsRequest_default_instance_;
PROTOBUF_CONSTEXPR SetDatapointsReply_ErrorsEntry_DoNotUse::SetDatapointsReply_ErrorsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct SetDatapointsReply_ErrorsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetDatapointsReply_ErrorsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetDatapointsReply_ErrorsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    SetDatapointsReply_ErrorsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetDatapointsReply_ErrorsEntry_DoNotUseDefaultTypeInternal _SetDatapointsReply_ErrorsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR SetDatapointsReply::SetDatapointsReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.errors_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SetDatapointsReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetDatapointsReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetDatapointsReplyDefaultTypeInternal() {}
  union {
    SetDatapointsReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetDatapointsReplyDefaultTypeInternal _SetDatapointsReply_default_instance_;
PROTOBUF_CONSTEXPR SubscribeRequest::SubscribeRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.query_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SubscribeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubscribeRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubscribeRequestDefaultTypeInternal() {}
  union {
    SubscribeRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubscribeRequestDefaultTypeInternal _SubscribeRequest_default_instance_;
PROTOBUF_CONSTEXPR SubscribeReply_FieldsEntry_DoNotUse::SubscribeReply_FieldsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct SubscribeReply_FieldsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubscribeReply_FieldsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubscribeReply_FieldsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    SubscribeReply_FieldsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubscribeReply_FieldsEntry_DoNotUseDefaultTypeInternal _SubscribeReply_FieldsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR SubscribeReply::SubscribeReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.fields_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SubscribeReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubscribeReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubscribeReplyDefaultTypeInternal() {}
  union {
    SubscribeReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubscribeReplyDefaultTypeInternal _SubscribeReply_default_instance_;
PROTOBUF_CONSTEXPR GetMetadataRequest::GetMetadataRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.names_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetMetadataRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetMetadataRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetMetadataRequestDefaultTypeInternal() {}
  union {
    GetMetadataRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetMetadataRequestDefaultTypeInternal _GetMetadataRequest_default_instance_;
PROTOBUF_CONSTEXPR GetMetadataReply::GetMetadataReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.list_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetMetadataReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetMetadataReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetMetadataReplyDefaultTypeInternal() {}
  union {
    GetMetadataReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetMetadataReplyDefaultTypeInternal _GetMetadataReply_default_instance_;
}  // namespace v1
}  // namespace databroker
}  // namespace sdv
static ::_pb::Metadata file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[12];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sdv_2fdatabroker_2fv1_2fbroker_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sdv_2fdatabroker_2fv1_2fbroker_2eproto = nullptr;

const uint32_t TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetDatapointsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetDatapointsRequest, _impl_.datapoints_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetDatapointsReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetDatapointsReply, _impl_.datapoints_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsRequest, _impl_.datapoints_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SetDatapointsReply, _impl_.errors_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SubscribeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SubscribeRequest, _impl_.query_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SubscribeReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::SubscribeReply, _impl_.fields_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetMetadataRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetMetadataRequest, _impl_.names_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetMetadataReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sdv::databroker::v1::GetMetadataReply, _impl_.list_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::sdv::databroker::v1::GetDatapointsRequest)},
  { 7, 15, -1, sizeof(::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse)},
  { 17, -1, -1, sizeof(::sdv::databroker::v1::GetDatapointsReply)},
  { 24, 32, -1, sizeof(::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse)},
  { 34, -1, -1, sizeof(::sdv::databroker::v1::SetDatapointsRequest)},
  { 41, 49, -1, sizeof(::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse)},
  { 51, -1, -1, sizeof(::sdv::databroker::v1::SetDatapointsReply)},
  { 58, -1, -1, sizeof(::sdv::databroker::v1::SubscribeRequest)},
  { 65, 73, -1, sizeof(::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse)},
  { 75, -1, -1, sizeof(::sdv::databroker::v1::SubscribeReply)},
  { 82, -1, -1, sizeof(::sdv::databroker::v1::GetMetadataRequest)},
  { 89, -1, -1, sizeof(::sdv::databroker::v1::GetMetadataReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sdv::databroker::v1::_GetDatapointsRequest_default_instance_._instance,
  &::sdv::databroker::v1::_GetDatapointsReply_DatapointsEntry_DoNotUse_default_instance_._instance,
  &::sdv::databroker::v1::_GetDatapointsReply_default_instance_._instance,
  &::sdv::databroker::v1::_SetDatapointsRequest_DatapointsEntry_DoNotUse_default_instance_._instance,
  &::sdv::databroker::v1::_SetDatapointsRequest_default_instance_._instance,
  &::sdv::databroker::v1::_SetDatapointsReply_ErrorsEntry_DoNotUse_default_instance_._instance,
  &::sdv::databroker::v1::_SetDatapointsReply_default_instance_._instance,
  &::sdv::databroker::v1::_SubscribeRequest_default_instance_._instance,
  &::sdv::databroker::v1::_SubscribeReply_FieldsEntry_DoNotUse_default_instance_._instance,
  &::sdv::databroker::v1::_SubscribeReply_default_instance_._instance,
  &::sdv::databroker::v1::_GetMetadataRequest_default_instance_._instance,
  &::sdv::databroker::v1::_GetMetadataReply_default_instance_._instance,
};

const char descriptor_table_protodef_sdv_2fdatabroker_2fv1_2fbroker_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036sdv/databroker/v1/broker.proto\022\021sdv.da"
  "tabroker.v1\032\035sdv/databroker/v1/types.pro"
  "to\"*\n\024GetDatapointsRequest\022\022\n\ndatapoints"
  "\030\001 \003(\t\"\260\001\n\022GetDatapointsReply\022I\n\ndatapoi"
  "nts\030\001 \003(\01325.sdv.databroker.v1.GetDatapoi"
  "ntsReply.DatapointsEntry\032O\n\017DatapointsEn"
  "try\022\013\n\003key\030\001 \001(\t\022+\n\005value\030\002 \001(\0132\034.sdv.da"
  "tabroker.v1.Datapoint:\0028\001\"\264\001\n\024SetDatapoi"
  "ntsRequest\022K\n\ndatapoints\030\001 \003(\01327.sdv.dat"
  "abroker.v1.SetDatapointsRequest.Datapoin"
  "tsEntry\032O\n\017DatapointsEntry\022\013\n\003key\030\001 \001(\t\022"
  "+\n\005value\030\002 \001(\0132\034.sdv.databroker.v1.Datap"
  "oint:\0028\001\"\251\001\n\022SetDatapointsReply\022A\n\006error"
  "s\030\001 \003(\01321.sdv.databroker.v1.SetDatapoint"
  "sReply.ErrorsEntry\032P\n\013ErrorsEntry\022\013\n\003key"
  "\030\001 \001(\t\0220\n\005value\030\002 \001(\0162!.sdv.databroker.v"
  "1.DatapointError:\0028\001\"!\n\020SubscribeRequest"
  "\022\r\n\005query\030\002 \001(\t\"\234\001\n\016SubscribeReply\022=\n\006fi"
  "elds\030\001 \003(\0132-.sdv.databroker.v1.Subscribe"
  "Reply.FieldsEntry\032K\n\013FieldsEntry\022\013\n\003key\030"
  "\001 \001(\t\022+\n\005value\030\002 \001(\0132\034.sdv.databroker.v1"
  ".Datapoint:\0028\001\"#\n\022GetMetadataRequest\022\r\n\005"
  "names\030\001 \003(\t\"=\n\020GetMetadataReply\022)\n\004list\030"
  "\001 \003(\0132\033.sdv.databroker.v1.Metadata2\374\002\n\006B"
  "roker\022_\n\rGetDatapoints\022\'.sdv.databroker."
  "v1.GetDatapointsRequest\032%.sdv.databroker"
  ".v1.GetDatapointsReply\022_\n\rSetDatapoints\022"
  "\'.sdv.databroker.v1.SetDatapointsRequest"
  "\032%.sdv.databroker.v1.SetDatapointsReply\022"
  "U\n\tSubscribe\022#.sdv.databroker.v1.Subscri"
  "beRequest\032!.sdv.databroker.v1.SubscribeR"
  "eply0\001\022Y\n\013GetMetadata\022%.sdv.databroker.v"
  "1.GetMetadataRequest\032#.sdv.databroker.v1"
  ".GetMetadataReplyb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_deps[1] = {
  &::descriptor_table_sdv_2fdatabroker_2fv1_2ftypes_2eproto,
};
static ::_pbi::once_flag descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto = {
    false, false, 1345, descriptor_table_protodef_sdv_2fdatabroker_2fv1_2fbroker_2eproto,
    "sdv/databroker/v1/broker.proto",
    &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once, descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_deps, 1, 12,
    schemas, file_default_instances, TableStruct_sdv_2fdatabroker_2fv1_2fbroker_2eproto::offsets,
    file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto, file_level_enum_descriptors_sdv_2fdatabroker_2fv1_2fbroker_2eproto,
    file_level_service_descriptors_sdv_2fdatabroker_2fv1_2fbroker_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter() {
  return &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sdv_2fdatabroker_2fv1_2fbroker_2eproto(&descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto);
namespace sdv {
namespace databroker {
namespace v1 {

// ===================================================================

class GetDatapointsRequest::_Internal {
 public:
};

GetDatapointsRequest::GetDatapointsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sdv.databroker.v1.GetDatapointsRequest)
}
GetDatapointsRequest::GetDatapointsRequest(const GetDatapointsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetDatapointsRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.datapoints_){from._impl_.datapoints_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sdv.databroker.v1.GetDatapointsRequest)
}

inline void GetDatapointsRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.datapoints_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetDatapointsRequest::~GetDatapointsRequest() {
  // @@protoc_insertion_point(destructor:sdv.databroker.v1.GetDatapointsRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetDatapointsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.datapoints_.~RepeatedPtrField();
}

void GetDatapointsRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetDatapointsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sdv.databroker.v1.GetDatapointsRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.datapoints_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetDatapointsRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string datapoints = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_datapoints();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "sdv.databroker.v1.GetDatapointsRequest.datapoints"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetDatapointsRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sdv.databroker.v1.GetDatapointsRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string datapoints = 1;
  for (int i = 0, n = this->_internal_datapoints_size(); i < n; i++) {
    const auto& s = this->_internal_datapoints(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sdv.databroker.v1.GetDatapointsRequest.datapoints");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sdv.databroker.v1.GetDatapointsRequest)
  return target;
}

size_t GetDatapointsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sdv.databroker.v1.GetDatapointsRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string datapoints = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.datapoints_.size());
  for (int i = 0, n = _impl_.datapoints_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.datapoints_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetDatapointsRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetDatapointsRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetDatapointsRequest::GetClassData() const { return &_class_data_; }


void GetDatapointsRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetDatapointsRequest*>(&to_msg);
  auto& from = static_cast<const GetDatapointsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sdv.databroker.v1.GetDatapointsRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.datapoints_.MergeFrom(from._impl_.datapoints_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetDatapointsRequest::CopyFrom(const GetDatapointsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sdv.databroker.v1.GetDatapointsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetDatapointsRequest::IsInitialized() const {
  return true;
}

void GetDatapointsRequest::InternalSwap(GetDatapointsRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.datapoints_.InternalSwap(&other->_impl_.datapoints_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetDatapointsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[0]);
}

// ===================================================================

GetDatapointsReply_DatapointsEntry_DoNotUse::GetDatapointsReply_DatapointsEntry_DoNotUse() {}
GetDatapointsReply_DatapointsEntry_DoNotUse::GetDatapointsReply_DatapointsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void GetDatapointsReply_DatapointsEntry_DoNotUse::MergeFrom(const GetDatapointsReply_DatapointsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata GetDatapointsReply_DatapointsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[1]);
}

// ===================================================================

class GetDatapointsReply::_Internal {
 public:
};

void GetDatapointsReply::clear_datapoints() {
  _impl_.datapoints_.Clear();
}
GetDatapointsReply::GetDatapointsReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &GetDatapointsReply::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:sdv.databroker.v1.GetDatapointsReply)
}
GetDatapointsReply::GetDatapointsReply(const GetDatapointsReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetDatapointsReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.datapoints_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.datapoints_.MergeFrom(from._impl_.datapoints_);
  // @@protoc_insertion_point(copy_constructor:sdv.databroker.v1.GetDatapointsReply)
}

inline void GetDatapointsReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.datapoints_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetDatapointsReply::~GetDatapointsReply() {
  // @@protoc_insertion_point(destructor:sdv.databroker.v1.GetDatapointsReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void GetDatapointsReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.datapoints_.Destruct();
  _impl_.datapoints_.~MapField();
}

void GetDatapointsReply::ArenaDtor(void* object) {
  GetDatapointsReply* _this = reinterpret_cast< GetDatapointsReply* >(object);
  _this->_impl_.datapoints_.Destruct();
}
void GetDatapointsReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetDatapointsReply::Clear() {
// @@protoc_insertion_point(message_clear_start:sdv.databroker.v1.GetDatapointsReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.datapoints_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetDatapointsReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.datapoints_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetDatapointsReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sdv.databroker.v1.GetDatapointsReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
  if (!this->_internal_datapoints().empty()) {
    using MapType = ::_pb::Map<std::string, ::sdv::databroker::v1::Datapoint>;
    using WireHelper = GetDatapointsReply_DatapointsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_datapoints();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "sdv.databroker.v1.GetDatapointsReply.DatapointsEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sdv.databroker.v1.GetDatapointsReply)
  return target;
}

size_t GetDatapointsReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sdv.databroker.v1.GetDatapointsReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_datapoints_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >::const_iterator
      it = this->_internal_datapoints().begin();
      it != this->_internal_datapoints().end(); ++it) {
    total_size += GetDatapointsReply_DatapointsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetDatapointsReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetDatapointsReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetDatapointsReply::GetClassData() const { return &_class_data_; }


void GetDatapointsReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetDatapointsReply*>(&to_msg);
  auto& from = static_cast<const GetDatapointsReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sdv.databroker.v1.GetDatapointsReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.datapoints_.MergeFrom(from._impl_.datapoints_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetDatapointsReply::CopyFrom(const GetDatapointsReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sdv.databroker.v1.GetDatapointsReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetDatapointsReply::IsInitialized() const {
  return true;
}

void GetDatapointsReply::InternalSwap(GetDatapointsReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.datapoints_.InternalSwap(&other->_impl_.datapoints_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetDatapointsReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[2]);
}

// ===================================================================

SetDatapointsRequest_DatapointsEntry_DoNotUse::SetDatapointsRequest_DatapointsEntry_DoNotUse() {}
SetDatapointsRequest_DatapointsEntry_DoNotUse::SetDatapointsRequest_DatapointsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void SetDatapointsRequest_DatapointsEntry_DoNotUse::MergeFrom(const SetDatapointsRequest_DatapointsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata SetDatapointsRequest_DatapointsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[3]);
}

// ===================================================================

class SetDatapointsRequest::_Internal {
 public:
};

void SetDatapointsRequest::clear_datapoints() {
  _impl_.datapoints_.Clear();
}
SetDatapointsRequest::SetDatapointsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &SetDatapointsRequest::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:sdv.databroker.v1.SetDatapointsRequest)
}
SetDatapointsRequest::SetDatapointsRequest(const SetDatapointsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SetDatapointsRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.datapoints_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.datapoints_.MergeFrom(from._impl_.datapoints_);
  // @@protoc_insertion_point(copy_constructor:sdv.databroker.v1.SetDatapointsRequest)
}

inline void SetDatapointsRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.datapoints_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SetDatapointsRequest::~SetDatapointsRequest() {
  // @@protoc_insertion_point(destructor:sdv.databroker.v1.SetDatapointsRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void SetDatapointsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.datapoints_.Destruct();
  _impl_.datapoints_.~MapField();
}

void SetDatapointsRequest::ArenaDtor(void* object) {
  SetDatapointsRequest* _this = reinterpret_cast< SetDatapointsRequest* >(object);
  _this->_impl_.datapoints_.Destruct();
}
void SetDatapointsRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SetDatapointsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sdv.databroker.v1.SetDatapointsRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.datapoints_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetDatapointsRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.datapoints_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SetDatapointsRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sdv.databroker.v1.SetDatapointsRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
  if (!this->_internal_datapoints().empty()) {
    using MapType = ::_pb::Map<std::string, ::sdv::databroker::v1::Datapoint>;
    using WireHelper = SetDatapointsRequest_DatapointsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_datapoints();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "sdv.databroker.v1.SetDatapointsRequest.DatapointsEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sdv.databroker.v1.SetDatapointsRequest)
  return target;
}

size_t SetDatapointsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sdv.databroker.v1.SetDatapointsRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .sdv.databroker.v1.Datapoint> datapoints = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_datapoints_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >::const_iterator
      it = this->_internal_datapoints().begin();
      it != this->_internal_datapoints().end(); ++it) {
    total_size += SetDatapointsRequest_DatapointsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SetDatapointsRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SetDatapointsRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SetDatapointsRequest::GetClassData() const { return &_class_data_; }


void SetDatapointsRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SetDatapointsRequest*>(&to_msg);
  auto& from = static_cast<const SetDatapointsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sdv.databroker.v1.SetDatapointsRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.datapoints_.MergeFrom(from._impl_.datapoints_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SetDatapointsRequest::CopyFrom(const SetDatapointsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sdv.databroker.v1.SetDatapointsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetDatapointsRequest::IsInitialized() const {
  return true;
}

void SetDatapointsRequest::InternalSwap(SetDatapointsRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.datapoints_.InternalSwap(&other->_impl_.datapoints_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SetDatapointsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[4]);
}

// ===================================================================

SetDatapointsReply_ErrorsEntry_DoNotUse::SetDatapointsReply_ErrorsEntry_DoNotUse() {}
SetDatapointsReply_ErrorsEntry_DoNotUse::SetDatapointsReply_ErrorsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void SetDatapointsReply_ErrorsEntry_DoNotUse::MergeFrom(const SetDatapointsReply_ErrorsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata SetDatapointsReply_ErrorsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[5]);
}

// ===================================================================

class SetDatapointsReply::_Internal {
 public:
};

SetDatapointsReply::SetDatapointsReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &SetDatapointsReply::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:sdv.databroker.v1.SetDatapointsReply)
}
SetDatapointsReply::SetDatapointsReply(const SetDatapointsReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SetDatapointsReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.errors_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.errors_.MergeFrom(from._impl_.errors_);
  // @@protoc_insertion_point(copy_constructor:sdv.databroker.v1.SetDatapointsReply)
}

inline void SetDatapointsReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.errors_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SetDatapointsReply::~SetDatapointsReply() {
  // @@protoc_insertion_point(destructor:sdv.databroker.v1.SetDatapointsReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void SetDatapointsReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.errors_.Destruct();
  _impl_.errors_.~MapField();
}

void SetDatapointsReply::ArenaDtor(void* object) {
  SetDatapointsReply* _this = reinterpret_cast< SetDatapointsReply* >(object);
  _this->_impl_.errors_.Destruct();
}
void SetDatapointsReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SetDatapointsReply::Clear() {
// @@protoc_insertion_point(message_clear_start:sdv.databroker.v1.SetDatapointsReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.errors_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetDatapointsReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, .sdv.databroker.v1.DatapointError> errors = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.errors_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SetDatapointsReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sdv.databroker.v1.SetDatapointsReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .sdv.databroker.v1.DatapointError> errors = 1;
  if (!this->_internal_errors().empty()) {
    using MapType = ::_pb::Map<std::string, ::sdv::databroker::v1::DatapointError>;
    using WireHelper = SetDatapointsReply_ErrorsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_errors();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "sdv.databroker.v1.SetDatapointsReply.ErrorsEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sdv.databroker.v1.SetDatapointsReply)
  return target;
}

size_t SetDatapointsReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sdv.databroker.v1.SetDatapointsReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .sdv.databroker.v1.DatapointError> errors = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_errors_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::DatapointError >::const_iterator
      it = this->_internal_errors().begin();
      it != this->_internal_errors().end(); ++it) {
    total_size += SetDatapointsReply_ErrorsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SetDatapointsReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SetDatapointsReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SetDatapointsReply::GetClassData() const { return &_class_data_; }


void SetDatapointsReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SetDatapointsReply*>(&to_msg);
  auto& from = static_cast<const SetDatapointsReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sdv.databroker.v1.SetDatapointsReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.errors_.MergeFrom(from._impl_.errors_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SetDatapointsReply::CopyFrom(const SetDatapointsReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sdv.databroker.v1.SetDatapointsReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetDatapointsReply::IsInitialized() const {
  return true;
}

void SetDatapointsReply::InternalSwap(SetDatapointsReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.errors_.InternalSwap(&other->_impl_.errors_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SetDatapointsReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[6]);
}

// ===================================================================

class SubscribeRequest::_Internal {
 public:
};

SubscribeRequest::SubscribeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sdv.databroker.v1.SubscribeRequest)
}
SubscribeRequest::SubscribeRequest(const SubscribeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SubscribeRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.query_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.query_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.query_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_query().empty()) {
    _this->_impl_.query_.Set(from._internal_query(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:sdv.databroker.v1.SubscribeRequest)
}

inline void SubscribeRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.query_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.query_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.query_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SubscribeRequest::~SubscribeRequest() {
  // @@protoc_insertion_point(destructor:sdv.databroker.v1.SubscribeRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SubscribeRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.query_.Destroy();
}

void SubscribeRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SubscribeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sdv.databroker.v1.SubscribeRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.query_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SubscribeRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string query = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_query();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sdv.databroker.v1.SubscribeRequest.query"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SubscribeRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sdv.databroker.v1.SubscribeRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string query = 2;
  if (!this->_internal_query().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_query().data(), static_cast<int>(this->_internal_query().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sdv.databroker.v1.SubscribeRequest.query");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_query(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sdv.databroker.v1.SubscribeRequest)
  return target;
}

size_t SubscribeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sdv.databroker.v1.SubscribeRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string query = 2;
  if (!this->_internal_query().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_query());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SubscribeRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SubscribeRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SubscribeRequest::GetClassData() const { return &_class_data_; }


void SubscribeRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SubscribeRequest*>(&to_msg);
  auto& from = static_cast<const SubscribeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sdv.databroker.v1.SubscribeRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_query().empty()) {
    _this->_internal_set_query(from._internal_query());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SubscribeRequest::CopyFrom(const SubscribeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sdv.databroker.v1.SubscribeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubscribeRequest::IsInitialized() const {
  return true;
}

void SubscribeRequest::InternalSwap(SubscribeRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.query_, lhs_arena,
      &other->_impl_.query_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SubscribeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[7]);
}

// ===================================================================

SubscribeReply_FieldsEntry_DoNotUse::SubscribeReply_FieldsEntry_DoNotUse() {}
SubscribeReply_FieldsEntry_DoNotUse::SubscribeReply_FieldsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void SubscribeReply_FieldsEntry_DoNotUse::MergeFrom(const SubscribeReply_FieldsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata SubscribeReply_FieldsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[8]);
}

// ===================================================================

class SubscribeReply::_Internal {
 public:
};

void SubscribeReply::clear_fields() {
  _impl_.fields_.Clear();
}
SubscribeReply::SubscribeReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &SubscribeReply::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:sdv.databroker.v1.SubscribeReply)
}
SubscribeReply::SubscribeReply(const SubscribeReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SubscribeReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.fields_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.fields_.MergeFrom(from._impl_.fields_);
  // @@protoc_insertion_point(copy_constructor:sdv.databroker.v1.SubscribeReply)
}

inline void SubscribeReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.fields_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SubscribeReply::~SubscribeReply() {
  // @@protoc_insertion_point(destructor:sdv.databroker.v1.SubscribeReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void SubscribeReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.fields_.Destruct();
  _impl_.fields_.~MapField();
}

void SubscribeReply::ArenaDtor(void* object) {
  SubscribeReply* _this = reinterpret_cast< SubscribeReply* >(object);
  _this->_impl_.fields_.Destruct();
}
void SubscribeReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SubscribeReply::Clear() {
// @@protoc_insertion_point(message_clear_start:sdv.databroker.v1.SubscribeReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fields_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SubscribeReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, .sdv.databroker.v1.Datapoint> fields = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.fields_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SubscribeReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sdv.databroker.v1.SubscribeReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .sdv.databroker.v1.Datapoint> fields = 1;
  if (!this->_internal_fields().empty()) {
    using MapType = ::_pb::Map<std::string, ::sdv::databroker::v1::Datapoint>;
    using WireHelper = SubscribeReply_FieldsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_fields();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "sdv.databroker.v1.SubscribeReply.FieldsEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sdv.databroker.v1.SubscribeReply)
  return target;
}

size_t SubscribeReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sdv.databroker.v1.SubscribeReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .sdv.databroker.v1.Datapoint> fields = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_fields_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::sdv::databroker::v1::Datapoint >::const_iterator
      it = this->_internal_fields().begin();
      it != this->_internal_fields().end(); ++it) {
    total_size += SubscribeReply_FieldsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SubscribeReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SubscribeReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SubscribeReply::GetClassData() const { return &_class_data_; }


void SubscribeReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SubscribeReply*>(&to_msg);
  auto& from = static_cast<const SubscribeReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sdv.databroker.v1.SubscribeReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.fields_.MergeFrom(from._impl_.fields_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SubscribeReply::CopyFrom(const SubscribeReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sdv.databroker.v1.SubscribeReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubscribeReply::IsInitialized() const {
  return true;
}

void SubscribeReply::InternalSwap(SubscribeReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.fields_.InternalSwap(&other->_impl_.fields_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SubscribeReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[9]);
}

// ===================================================================

class GetMetadataRequest::_Internal {
 public:
};

GetMetadataRequest::GetMetadataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sdv.databroker.v1.GetMetadataRequest)
}
GetMetadataRequest::GetMetadataRequest(const GetMetadataRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetMetadataRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.names_){from._impl_.names_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sdv.databroker.v1.GetMetadataRequest)
}

inline void GetMetadataRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.names_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetMetadataRequest::~GetMetadataRequest() {
  // @@protoc_insertion_point(destructor:sdv.databroker.v1.GetMetadataRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetMetadataRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.names_.~RepeatedPtrField();
}

void GetMetadataRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetMetadataRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sdv.databroker.v1.GetMetadataRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.names_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetMetadataRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string names = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_names();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "sdv.databroker.v1.GetMetadataRequest.names"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetMetadataRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sdv.databroker.v1.GetMetadataRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string names = 1;
  for (int i = 0, n = this->_internal_names_size(); i < n; i++) {
    const auto& s = this->_internal_names(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sdv.databroker.v1.GetMetadataRequest.names");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sdv.databroker.v1.GetMetadataRequest)
  return target;
}

size_t GetMetadataRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sdv.databroker.v1.GetMetadataRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string names = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.names_.size());
  for (int i = 0, n = _impl_.names_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.names_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetMetadataRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetMetadataRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetMetadataRequest::GetClassData() const { return &_class_data_; }


void GetMetadataRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetMetadataRequest*>(&to_msg);
  auto& from = static_cast<const GetMetadataRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sdv.databroker.v1.GetMetadataRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.names_.MergeFrom(from._impl_.names_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetMetadataRequest::CopyFrom(const GetMetadataRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sdv.databroker.v1.GetMetadataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetMetadataRequest::IsInitialized() const {
  return true;
}

void GetMetadataRequest::InternalSwap(GetMetadataRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.names_.InternalSwap(&other->_impl_.names_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[10]);
}

// ===================================================================

class GetMetadataReply::_Internal {
 public:
};

void GetMetadataReply::clear_list() {
  _impl_.list_.Clear();
}
GetMetadataReply::GetMetadataReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sdv.databroker.v1.GetMetadataReply)
}
GetMetadataReply::GetMetadataReply(const GetMetadataReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetMetadataReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.list_){from._impl_.list_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sdv.databroker.v1.GetMetadataReply)
}

inline void GetMetadataReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.list_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetMetadataReply::~GetMetadataReply() {
  // @@protoc_insertion_point(destructor:sdv.databroker.v1.GetMetadataReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetMetadataReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.list_.~RepeatedPtrField();
}

void GetMetadataReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetMetadataReply::Clear() {
// @@protoc_insertion_point(message_clear_start:sdv.databroker.v1.GetMetadataReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.list_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetMetadataReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .sdv.databroker.v1.Metadata list = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_list(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetMetadataReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sdv.databroker.v1.GetMetadataReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .sdv.databroker.v1.Metadata list = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_list_size()); i < n; i++) {
    const auto& repfield = this->_internal_list(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sdv.databroker.v1.GetMetadataReply)
  return target;
}

size_t GetMetadataReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sdv.databroker.v1.GetMetadataReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .sdv.databroker.v1.Metadata list = 1;
  total_size += 1UL * this->_internal_list_size();
  for (const auto& msg : this->_impl_.list_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetMetadataReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetMetadataReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetMetadataReply::GetClassData() const { return &_class_data_; }


void GetMetadataReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetMetadataReply*>(&to_msg);
  auto& from = static_cast<const GetMetadataReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sdv.databroker.v1.GetMetadataReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.list_.MergeFrom(from._impl_.list_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetMetadataReply::CopyFrom(const GetMetadataReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sdv.databroker.v1.GetMetadataReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetMetadataReply::IsInitialized() const {
  return true;
}

void GetMetadataReply::InternalSwap(GetMetadataReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.list_.InternalSwap(&other->_impl_.list_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_getter, &descriptor_table_sdv_2fdatabroker_2fv1_2fbroker_2eproto_once,
      file_level_metadata_sdv_2fdatabroker_2fv1_2fbroker_2eproto[11]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace databroker
}  // namespace sdv
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::GetDatapointsRequest*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::GetDatapointsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::GetDatapointsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::GetDatapointsReply_DatapointsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::GetDatapointsReply*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::GetDatapointsReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::GetDatapointsReply >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::SetDatapointsRequest_DatapointsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::SetDatapointsRequest*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::SetDatapointsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::SetDatapointsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::SetDatapointsReply_ErrorsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::SetDatapointsReply*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::SetDatapointsReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::SetDatapointsReply >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::SubscribeRequest*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::SubscribeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::SubscribeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::SubscribeReply_FieldsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::SubscribeReply*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::SubscribeReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::SubscribeReply >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::GetMetadataRequest*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::GetMetadataRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::GetMetadataRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::sdv::databroker::v1::GetMetadataReply*
Arena::CreateMaybeMessage< ::sdv::databroker::v1::GetMetadataReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sdv::databroker::v1::GetMetadataReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
