// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sdv/databroker/v1/collector.proto

#include "sdv/databroker/v1/collector.pb.h"
#include "sdv/databroker/v1/collector.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace sdv {
namespace databroker {
namespace v1 {

class MockCollectorStub : public Collector::StubInterface {
 public:
  MOCK_METHOD3(RegisterDatapoints, ::grpc::Status(::grpc::ClientContext* context, const ::sdv::databroker::v1::RegisterDatapointsRequest& request, ::sdv::databroker::v1::RegisterDatapointsReply* response));
  MOCK_METHOD3(AsyncRegisterDatapointsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::RegisterDatapointsReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::RegisterDatapointsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncRegisterDatapointsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::RegisterDatapointsReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::RegisterDatapointsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(UpdateDatapoints, ::grpc::Status(::grpc::ClientContext* context, const ::sdv::databroker::v1::UpdateDatapointsRequest& request, ::sdv::databroker::v1::UpdateDatapointsReply* response));
  MOCK_METHOD3(AsyncUpdateDatapointsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::UpdateDatapointsReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::UpdateDatapointsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncUpdateDatapointsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::sdv::databroker::v1::UpdateDatapointsReply>*(::grpc::ClientContext* context, const ::sdv::databroker::v1::UpdateDatapointsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD1(StreamDatapointsRaw, ::grpc::ClientReaderWriterInterface< ::sdv::databroker::v1::StreamDatapointsRequest, ::sdv::databroker::v1::StreamDatapointsReply>*(::grpc::ClientContext* context));
  MOCK_METHOD3(AsyncStreamDatapointsRaw, ::grpc::ClientAsyncReaderWriterInterface<::sdv::databroker::v1::StreamDatapointsRequest, ::sdv::databroker::v1::StreamDatapointsReply>*(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD2(PrepareAsyncStreamDatapointsRaw, ::grpc::ClientAsyncReaderWriterInterface<::sdv::databroker::v1::StreamDatapointsRequest, ::sdv::databroker::v1::StreamDatapointsReply>*(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq));
};

} // namespace sdv
} // namespace databroker
} // namespace v1

