// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: duo/duo.proto

#include "duo/duo.pb.h"
#include "duo/duo.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace duo {

static const char* ShadowService_method_names[] = {
  "/duo.ShadowService/GetThingList",
  "/duo.ShadowService/GetReport",
  "/duo.ShadowService/GetDesire",
  "/duo.ShadowService/GetDelta",
  "/duo.ShadowService/PatchReport",
  "/duo.ShadowService/PatchDesire",
  "/duo.ShadowService/Delete",
  "/duo.ShadowService/Upload",
  "/duo.ShadowService/PatchDesireAndWait",
  "/duo.ShadowService/ListenReport",
  "/duo.ShadowService/ListenDesire",
  "/duo.ShadowService/ListenDelta",
  "/duo.ShadowService/Ping",
};

std::unique_ptr< ShadowService::Stub> ShadowService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ShadowService::Stub> stub(new ShadowService::Stub(channel, options));
  return stub;
}

ShadowService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetThingList_(ShadowService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetReport_(ShadowService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDesire_(ShadowService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDelta_(ShadowService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PatchReport_(ShadowService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PatchDesire_(ShadowService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(ShadowService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Upload_(ShadowService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_PatchDesireAndWait_(ShadowService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ListenReport_(ShadowService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ListenDesire_(ShadowService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ListenDelta_(ShadowService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Ping_(ShadowService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ShadowService::Stub::GetThingList(::grpc::ClientContext* context, const ::duo::GetThingListRequest& request, ::duo::GetThingListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::GetThingListRequest, ::duo::GetThingListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetThingList_, context, request, response);
}

void ShadowService::Stub::async::GetThingList(::grpc::ClientContext* context, const ::duo::GetThingListRequest* request, ::duo::GetThingListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::GetThingListRequest, ::duo::GetThingListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetThingList_, context, request, response, std::move(f));
}

void ShadowService::Stub::async::GetThingList(::grpc::ClientContext* context, const ::duo::GetThingListRequest* request, ::duo::GetThingListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetThingList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::GetThingListResponse>* ShadowService::Stub::PrepareAsyncGetThingListRaw(::grpc::ClientContext* context, const ::duo::GetThingListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::GetThingListResponse, ::duo::GetThingListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetThingList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::GetThingListResponse>* ShadowService::Stub::AsyncGetThingListRaw(::grpc::ClientContext* context, const ::duo::GetThingListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetThingListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ShadowService::Stub::GetReport(::grpc::ClientContext* context, const ::duo::GetReportRequest& request, ::duo::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::GetReportRequest, ::duo::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetReport_, context, request, response);
}

void ShadowService::Stub::async::GetReport(::grpc::ClientContext* context, const ::duo::GetReportRequest* request, ::duo::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::GetReportRequest, ::duo::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReport_, context, request, response, std::move(f));
}

void ShadowService::Stub::async::GetReport(::grpc::ClientContext* context, const ::duo::GetReportRequest* request, ::duo::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReport_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::GetResponse>* ShadowService::Stub::PrepareAsyncGetReportRaw(::grpc::ClientContext* context, const ::duo::GetReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::GetResponse, ::duo::GetReportRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetReport_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::GetResponse>* ShadowService::Stub::AsyncGetReportRaw(::grpc::ClientContext* context, const ::duo::GetReportRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetReportRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ShadowService::Stub::GetDesire(::grpc::ClientContext* context, const ::duo::GetDesireRequest& request, ::duo::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::GetDesireRequest, ::duo::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDesire_, context, request, response);
}

void ShadowService::Stub::async::GetDesire(::grpc::ClientContext* context, const ::duo::GetDesireRequest* request, ::duo::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::GetDesireRequest, ::duo::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDesire_, context, request, response, std::move(f));
}

void ShadowService::Stub::async::GetDesire(::grpc::ClientContext* context, const ::duo::GetDesireRequest* request, ::duo::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDesire_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::GetResponse>* ShadowService::Stub::PrepareAsyncGetDesireRaw(::grpc::ClientContext* context, const ::duo::GetDesireRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::GetResponse, ::duo::GetDesireRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDesire_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::GetResponse>* ShadowService::Stub::AsyncGetDesireRaw(::grpc::ClientContext* context, const ::duo::GetDesireRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDesireRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ShadowService::Stub::GetDelta(::grpc::ClientContext* context, const ::duo::GetDeltaRequest& request, ::duo::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::GetDeltaRequest, ::duo::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDelta_, context, request, response);
}

void ShadowService::Stub::async::GetDelta(::grpc::ClientContext* context, const ::duo::GetDeltaRequest* request, ::duo::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::GetDeltaRequest, ::duo::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDelta_, context, request, response, std::move(f));
}

void ShadowService::Stub::async::GetDelta(::grpc::ClientContext* context, const ::duo::GetDeltaRequest* request, ::duo::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDelta_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::GetResponse>* ShadowService::Stub::PrepareAsyncGetDeltaRaw(::grpc::ClientContext* context, const ::duo::GetDeltaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::GetResponse, ::duo::GetDeltaRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDelta_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::GetResponse>* ShadowService::Stub::AsyncGetDeltaRaw(::grpc::ClientContext* context, const ::duo::GetDeltaRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDeltaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ShadowService::Stub::PatchReport(::grpc::ClientContext* context, const ::duo::PatchReportRequest& request, ::duo::PatchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::PatchReportRequest, ::duo::PatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PatchReport_, context, request, response);
}

void ShadowService::Stub::async::PatchReport(::grpc::ClientContext* context, const ::duo::PatchReportRequest* request, ::duo::PatchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::PatchReportRequest, ::duo::PatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PatchReport_, context, request, response, std::move(f));
}

void ShadowService::Stub::async::PatchReport(::grpc::ClientContext* context, const ::duo::PatchReportRequest* request, ::duo::PatchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PatchReport_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::PatchResponse>* ShadowService::Stub::PrepareAsyncPatchReportRaw(::grpc::ClientContext* context, const ::duo::PatchReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::PatchResponse, ::duo::PatchReportRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PatchReport_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::PatchResponse>* ShadowService::Stub::AsyncPatchReportRaw(::grpc::ClientContext* context, const ::duo::PatchReportRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPatchReportRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ShadowService::Stub::PatchDesire(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::duo::PatchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::PatchDesireRequest, ::duo::PatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PatchDesire_, context, request, response);
}

void ShadowService::Stub::async::PatchDesire(::grpc::ClientContext* context, const ::duo::PatchDesireRequest* request, ::duo::PatchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::PatchDesireRequest, ::duo::PatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PatchDesire_, context, request, response, std::move(f));
}

void ShadowService::Stub::async::PatchDesire(::grpc::ClientContext* context, const ::duo::PatchDesireRequest* request, ::duo::PatchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PatchDesire_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::PatchResponse>* ShadowService::Stub::PrepareAsyncPatchDesireRaw(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::PatchResponse, ::duo::PatchDesireRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PatchDesire_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::PatchResponse>* ShadowService::Stub::AsyncPatchDesireRaw(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPatchDesireRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ShadowService::Stub::Delete(::grpc::ClientContext* context, const ::duo::DeleteRequest& request, ::duo::DeleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::DeleteRequest, ::duo::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Delete_, context, request, response);
}

void ShadowService::Stub::async::Delete(::grpc::ClientContext* context, const ::duo::DeleteRequest* request, ::duo::DeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::DeleteRequest, ::duo::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void ShadowService::Stub::async::Delete(::grpc::ClientContext* context, const ::duo::DeleteRequest* request, ::duo::DeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::DeleteResponse>* ShadowService::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::duo::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::DeleteResponse, ::duo::DeleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::DeleteResponse>* ShadowService::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::duo::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::duo::UploadRequest>* ShadowService::Stub::UploadRaw(::grpc::ClientContext* context, ::duo::UploadResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::duo::UploadRequest>::Create(channel_.get(), rpcmethod_Upload_, context, response);
}

void ShadowService::Stub::async::Upload(::grpc::ClientContext* context, ::duo::UploadResponse* response, ::grpc::ClientWriteReactor< ::duo::UploadRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::duo::UploadRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_Upload_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::duo::UploadRequest>* ShadowService::Stub::AsyncUploadRaw(::grpc::ClientContext* context, ::duo::UploadResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::duo::UploadRequest>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::duo::UploadRequest>* ShadowService::Stub::PrepareAsyncUploadRaw(::grpc::ClientContext* context, ::duo::UploadResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::duo::UploadRequest>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, false, nullptr);
}

::grpc::ClientReader< ::duo::PatchAndWaitResponse>* ShadowService::Stub::PatchDesireAndWaitRaw(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::duo::PatchAndWaitResponse>::Create(channel_.get(), rpcmethod_PatchDesireAndWait_, context, request);
}

void ShadowService::Stub::async::PatchDesireAndWait(::grpc::ClientContext* context, const ::duo::PatchDesireRequest* request, ::grpc::ClientReadReactor< ::duo::PatchAndWaitResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::duo::PatchAndWaitResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_PatchDesireAndWait_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::duo::PatchAndWaitResponse>* ShadowService::Stub::AsyncPatchDesireAndWaitRaw(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::PatchAndWaitResponse>::Create(channel_.get(), cq, rpcmethod_PatchDesireAndWait_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::duo::PatchAndWaitResponse>* ShadowService::Stub::PrepareAsyncPatchDesireAndWaitRaw(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::PatchAndWaitResponse>::Create(channel_.get(), cq, rpcmethod_PatchDesireAndWait_, context, request, false, nullptr);
}

::grpc::ClientReader< ::duo::ListenResponse>* ShadowService::Stub::ListenReportRaw(::grpc::ClientContext* context, const ::duo::ListenReportRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::duo::ListenResponse>::Create(channel_.get(), rpcmethod_ListenReport_, context, request);
}

void ShadowService::Stub::async::ListenReport(::grpc::ClientContext* context, const ::duo::ListenReportRequest* request, ::grpc::ClientReadReactor< ::duo::ListenResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::duo::ListenResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ListenReport_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::duo::ListenResponse>* ShadowService::Stub::AsyncListenReportRaw(::grpc::ClientContext* context, const ::duo::ListenReportRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenResponse>::Create(channel_.get(), cq, rpcmethod_ListenReport_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::duo::ListenResponse>* ShadowService::Stub::PrepareAsyncListenReportRaw(::grpc::ClientContext* context, const ::duo::ListenReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenResponse>::Create(channel_.get(), cq, rpcmethod_ListenReport_, context, request, false, nullptr);
}

::grpc::ClientReader< ::duo::ListenResponse>* ShadowService::Stub::ListenDesireRaw(::grpc::ClientContext* context, const ::duo::ListenDesireRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::duo::ListenResponse>::Create(channel_.get(), rpcmethod_ListenDesire_, context, request);
}

void ShadowService::Stub::async::ListenDesire(::grpc::ClientContext* context, const ::duo::ListenDesireRequest* request, ::grpc::ClientReadReactor< ::duo::ListenResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::duo::ListenResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ListenDesire_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::duo::ListenResponse>* ShadowService::Stub::AsyncListenDesireRaw(::grpc::ClientContext* context, const ::duo::ListenDesireRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenResponse>::Create(channel_.get(), cq, rpcmethod_ListenDesire_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::duo::ListenResponse>* ShadowService::Stub::PrepareAsyncListenDesireRaw(::grpc::ClientContext* context, const ::duo::ListenDesireRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenResponse>::Create(channel_.get(), cq, rpcmethod_ListenDesire_, context, request, false, nullptr);
}

::grpc::ClientReader< ::duo::ListenResponse>* ShadowService::Stub::ListenDeltaRaw(::grpc::ClientContext* context, const ::duo::ListenDeltaRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::duo::ListenResponse>::Create(channel_.get(), rpcmethod_ListenDelta_, context, request);
}

void ShadowService::Stub::async::ListenDelta(::grpc::ClientContext* context, const ::duo::ListenDeltaRequest* request, ::grpc::ClientReadReactor< ::duo::ListenResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::duo::ListenResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ListenDelta_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::duo::ListenResponse>* ShadowService::Stub::AsyncListenDeltaRaw(::grpc::ClientContext* context, const ::duo::ListenDeltaRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenResponse>::Create(channel_.get(), cq, rpcmethod_ListenDelta_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::duo::ListenResponse>* ShadowService::Stub::PrepareAsyncListenDeltaRaw(::grpc::ClientContext* context, const ::duo::ListenDeltaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenResponse>::Create(channel_.get(), cq, rpcmethod_ListenDelta_, context, request, false, nullptr);
}

::grpc::Status ShadowService::Stub::Ping(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::duo::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::PingRequest, ::duo::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void ShadowService::Stub::async::Ping(::grpc::ClientContext* context, const ::duo::PingRequest* request, ::duo::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::PingRequest, ::duo::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void ShadowService::Stub::async::Ping(::grpc::ClientContext* context, const ::duo::PingRequest* request, ::duo::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::PingResponse>* ShadowService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::PingResponse, ::duo::PingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::PingResponse>* ShadowService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

ShadowService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShadowService::Service, ::duo::GetThingListRequest, ::duo::GetThingListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::GetThingListRequest* req,
             ::duo::GetThingListResponse* resp) {
               return service->GetThingList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShadowService::Service, ::duo::GetReportRequest, ::duo::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::GetReportRequest* req,
             ::duo::GetResponse* resp) {
               return service->GetReport(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShadowService::Service, ::duo::GetDesireRequest, ::duo::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::GetDesireRequest* req,
             ::duo::GetResponse* resp) {
               return service->GetDesire(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShadowService::Service, ::duo::GetDeltaRequest, ::duo::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::GetDeltaRequest* req,
             ::duo::GetResponse* resp) {
               return service->GetDelta(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShadowService::Service, ::duo::PatchReportRequest, ::duo::PatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::PatchReportRequest* req,
             ::duo::PatchResponse* resp) {
               return service->PatchReport(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShadowService::Service, ::duo::PatchDesireRequest, ::duo::PatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::PatchDesireRequest* req,
             ::duo::PatchResponse* resp) {
               return service->PatchDesire(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShadowService::Service, ::duo::DeleteRequest, ::duo::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::DeleteRequest* req,
             ::duo::DeleteResponse* resp) {
               return service->Delete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[7],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< ShadowService::Service, ::duo::UploadRequest, ::duo::UploadResponse>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::duo::UploadRequest>* reader,
             ::duo::UploadResponse* resp) {
               return service->Upload(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[8],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ShadowService::Service, ::duo::PatchDesireRequest, ::duo::PatchAndWaitResponse>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::PatchDesireRequest* req,
             ::grpc::ServerWriter<::duo::PatchAndWaitResponse>* writer) {
               return service->PatchDesireAndWait(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[9],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ShadowService::Service, ::duo::ListenReportRequest, ::duo::ListenResponse>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::ListenReportRequest* req,
             ::grpc::ServerWriter<::duo::ListenResponse>* writer) {
               return service->ListenReport(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[10],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ShadowService::Service, ::duo::ListenDesireRequest, ::duo::ListenResponse>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::ListenDesireRequest* req,
             ::grpc::ServerWriter<::duo::ListenResponse>* writer) {
               return service->ListenDesire(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[11],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ShadowService::Service, ::duo::ListenDeltaRequest, ::duo::ListenResponse>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::ListenDeltaRequest* req,
             ::grpc::ServerWriter<::duo::ListenResponse>* writer) {
               return service->ListenDelta(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShadowService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShadowService::Service, ::duo::PingRequest, ::duo::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShadowService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::PingRequest* req,
             ::duo::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
}

ShadowService::Service::~Service() {
}

::grpc::Status ShadowService::Service::GetThingList(::grpc::ServerContext* context, const ::duo::GetThingListRequest* request, ::duo::GetThingListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::GetReport(::grpc::ServerContext* context, const ::duo::GetReportRequest* request, ::duo::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::GetDesire(::grpc::ServerContext* context, const ::duo::GetDesireRequest* request, ::duo::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::GetDelta(::grpc::ServerContext* context, const ::duo::GetDeltaRequest* request, ::duo::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::PatchReport(::grpc::ServerContext* context, const ::duo::PatchReportRequest* request, ::duo::PatchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::PatchDesire(::grpc::ServerContext* context, const ::duo::PatchDesireRequest* request, ::duo::PatchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::Delete(::grpc::ServerContext* context, const ::duo::DeleteRequest* request, ::duo::DeleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::Upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::duo::UploadRequest>* reader, ::duo::UploadResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::PatchDesireAndWait(::grpc::ServerContext* context, const ::duo::PatchDesireRequest* request, ::grpc::ServerWriter< ::duo::PatchAndWaitResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::ListenReport(::grpc::ServerContext* context, const ::duo::ListenReportRequest* request, ::grpc::ServerWriter< ::duo::ListenResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::ListenDesire(::grpc::ServerContext* context, const ::duo::ListenDesireRequest* request, ::grpc::ServerWriter< ::duo::ListenResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::ListenDelta(::grpc::ServerContext* context, const ::duo::ListenDeltaRequest* request, ::grpc::ServerWriter< ::duo::ListenResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShadowService::Service::Ping(::grpc::ServerContext* context, const ::duo::PingRequest* request, ::duo::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* JobService_method_names[] = {
  "/duo.JobService/GetJob",
  "/duo.JobService/GetNextJob",
  "/duo.JobService/GetUnfinishedJobs",
  "/duo.JobService/GetFinishedJobs",
  "/duo.JobService/CreateJob",
  "/duo.JobService/DeleteFinishedJobs",
  "/duo.JobService/UpdateJob",
  "/duo.JobService/ListenNextJobArrived",
  "/duo.JobService/ListenJobChanged",
  "/duo.JobService/Ping",
};

std::unique_ptr< JobService::Stub> JobService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< JobService::Stub> stub(new JobService::Stub(channel, options));
  return stub;
}

JobService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetJob_(JobService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNextJob_(JobService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUnfinishedJobs_(JobService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFinishedJobs_(JobService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateJob_(JobService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteFinishedJobs_(JobService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateJob_(JobService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListenNextJobArrived_(JobService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ListenJobChanged_(JobService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Ping_(JobService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status JobService::Stub::GetJob(::grpc::ClientContext* context, const ::duo::GetJobRequest& request, ::duo::GetJobResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::GetJobRequest, ::duo::GetJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetJob_, context, request, response);
}

void JobService::Stub::async::GetJob(::grpc::ClientContext* context, const ::duo::GetJobRequest* request, ::duo::GetJobResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::GetJobRequest, ::duo::GetJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetJob_, context, request, response, std::move(f));
}

void JobService::Stub::async::GetJob(::grpc::ClientContext* context, const ::duo::GetJobRequest* request, ::duo::GetJobResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::GetJobResponse>* JobService::Stub::PrepareAsyncGetJobRaw(::grpc::ClientContext* context, const ::duo::GetJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::GetJobResponse, ::duo::GetJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::GetJobResponse>* JobService::Stub::AsyncGetJobRaw(::grpc::ClientContext* context, const ::duo::GetJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status JobService::Stub::GetNextJob(::grpc::ClientContext* context, const ::duo::GetNextJobRequest& request, ::duo::GetJobResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::GetNextJobRequest, ::duo::GetJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNextJob_, context, request, response);
}

void JobService::Stub::async::GetNextJob(::grpc::ClientContext* context, const ::duo::GetNextJobRequest* request, ::duo::GetJobResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::GetNextJobRequest, ::duo::GetJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNextJob_, context, request, response, std::move(f));
}

void JobService::Stub::async::GetNextJob(::grpc::ClientContext* context, const ::duo::GetNextJobRequest* request, ::duo::GetJobResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNextJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::GetJobResponse>* JobService::Stub::PrepareAsyncGetNextJobRaw(::grpc::ClientContext* context, const ::duo::GetNextJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::GetJobResponse, ::duo::GetNextJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNextJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::GetJobResponse>* JobService::Stub::AsyncGetNextJobRaw(::grpc::ClientContext* context, const ::duo::GetNextJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNextJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status JobService::Stub::GetUnfinishedJobs(::grpc::ClientContext* context, const ::duo::GetUnfinishedJobsRequest& request, ::duo::GetJobsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::GetUnfinishedJobsRequest, ::duo::GetJobsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUnfinishedJobs_, context, request, response);
}

void JobService::Stub::async::GetUnfinishedJobs(::grpc::ClientContext* context, const ::duo::GetUnfinishedJobsRequest* request, ::duo::GetJobsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::GetUnfinishedJobsRequest, ::duo::GetJobsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUnfinishedJobs_, context, request, response, std::move(f));
}

void JobService::Stub::async::GetUnfinishedJobs(::grpc::ClientContext* context, const ::duo::GetUnfinishedJobsRequest* request, ::duo::GetJobsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUnfinishedJobs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::GetJobsResponse>* JobService::Stub::PrepareAsyncGetUnfinishedJobsRaw(::grpc::ClientContext* context, const ::duo::GetUnfinishedJobsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::GetJobsResponse, ::duo::GetUnfinishedJobsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUnfinishedJobs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::GetJobsResponse>* JobService::Stub::AsyncGetUnfinishedJobsRaw(::grpc::ClientContext* context, const ::duo::GetUnfinishedJobsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUnfinishedJobsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status JobService::Stub::GetFinishedJobs(::grpc::ClientContext* context, const ::duo::GetFinishedJobsRequest& request, ::duo::GetJobsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::GetFinishedJobsRequest, ::duo::GetJobsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFinishedJobs_, context, request, response);
}

void JobService::Stub::async::GetFinishedJobs(::grpc::ClientContext* context, const ::duo::GetFinishedJobsRequest* request, ::duo::GetJobsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::GetFinishedJobsRequest, ::duo::GetJobsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFinishedJobs_, context, request, response, std::move(f));
}

void JobService::Stub::async::GetFinishedJobs(::grpc::ClientContext* context, const ::duo::GetFinishedJobsRequest* request, ::duo::GetJobsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFinishedJobs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::GetJobsResponse>* JobService::Stub::PrepareAsyncGetFinishedJobsRaw(::grpc::ClientContext* context, const ::duo::GetFinishedJobsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::GetJobsResponse, ::duo::GetFinishedJobsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFinishedJobs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::GetJobsResponse>* JobService::Stub::AsyncGetFinishedJobsRaw(::grpc::ClientContext* context, const ::duo::GetFinishedJobsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFinishedJobsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status JobService::Stub::CreateJob(::grpc::ClientContext* context, const ::duo::CreateJobRequest& request, ::duo::CreateJobResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::CreateJobRequest, ::duo::CreateJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateJob_, context, request, response);
}

void JobService::Stub::async::CreateJob(::grpc::ClientContext* context, const ::duo::CreateJobRequest* request, ::duo::CreateJobResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::CreateJobRequest, ::duo::CreateJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateJob_, context, request, response, std::move(f));
}

void JobService::Stub::async::CreateJob(::grpc::ClientContext* context, const ::duo::CreateJobRequest* request, ::duo::CreateJobResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::CreateJobResponse>* JobService::Stub::PrepareAsyncCreateJobRaw(::grpc::ClientContext* context, const ::duo::CreateJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::CreateJobResponse, ::duo::CreateJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::CreateJobResponse>* JobService::Stub::AsyncCreateJobRaw(::grpc::ClientContext* context, const ::duo::CreateJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status JobService::Stub::DeleteFinishedJobs(::grpc::ClientContext* context, const ::duo::DeleteFinishedJobsRequest& request, ::duo::JobDeleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::DeleteFinishedJobsRequest, ::duo::JobDeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteFinishedJobs_, context, request, response);
}

void JobService::Stub::async::DeleteFinishedJobs(::grpc::ClientContext* context, const ::duo::DeleteFinishedJobsRequest* request, ::duo::JobDeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::DeleteFinishedJobsRequest, ::duo::JobDeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFinishedJobs_, context, request, response, std::move(f));
}

void JobService::Stub::async::DeleteFinishedJobs(::grpc::ClientContext* context, const ::duo::DeleteFinishedJobsRequest* request, ::duo::JobDeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFinishedJobs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::JobDeleteResponse>* JobService::Stub::PrepareAsyncDeleteFinishedJobsRaw(::grpc::ClientContext* context, const ::duo::DeleteFinishedJobsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::JobDeleteResponse, ::duo::DeleteFinishedJobsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteFinishedJobs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::JobDeleteResponse>* JobService::Stub::AsyncDeleteFinishedJobsRaw(::grpc::ClientContext* context, const ::duo::DeleteFinishedJobsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteFinishedJobsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status JobService::Stub::UpdateJob(::grpc::ClientContext* context, const ::duo::UpdateJobRequest& request, ::duo::UpdateJobResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::UpdateJobRequest, ::duo::UpdateJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateJob_, context, request, response);
}

void JobService::Stub::async::UpdateJob(::grpc::ClientContext* context, const ::duo::UpdateJobRequest* request, ::duo::UpdateJobResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::UpdateJobRequest, ::duo::UpdateJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateJob_, context, request, response, std::move(f));
}

void JobService::Stub::async::UpdateJob(::grpc::ClientContext* context, const ::duo::UpdateJobRequest* request, ::duo::UpdateJobResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::UpdateJobResponse>* JobService::Stub::PrepareAsyncUpdateJobRaw(::grpc::ClientContext* context, const ::duo::UpdateJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::UpdateJobResponse, ::duo::UpdateJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::UpdateJobResponse>* JobService::Stub::AsyncUpdateJobRaw(::grpc::ClientContext* context, const ::duo::UpdateJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::duo::ListenNextJobArrivedResponse>* JobService::Stub::ListenNextJobArrivedRaw(::grpc::ClientContext* context, const ::duo::ListenNextJobArrivedRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::duo::ListenNextJobArrivedResponse>::Create(channel_.get(), rpcmethod_ListenNextJobArrived_, context, request);
}

void JobService::Stub::async::ListenNextJobArrived(::grpc::ClientContext* context, const ::duo::ListenNextJobArrivedRequest* request, ::grpc::ClientReadReactor< ::duo::ListenNextJobArrivedResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::duo::ListenNextJobArrivedResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ListenNextJobArrived_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::duo::ListenNextJobArrivedResponse>* JobService::Stub::AsyncListenNextJobArrivedRaw(::grpc::ClientContext* context, const ::duo::ListenNextJobArrivedRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenNextJobArrivedResponse>::Create(channel_.get(), cq, rpcmethod_ListenNextJobArrived_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::duo::ListenNextJobArrivedResponse>* JobService::Stub::PrepareAsyncListenNextJobArrivedRaw(::grpc::ClientContext* context, const ::duo::ListenNextJobArrivedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenNextJobArrivedResponse>::Create(channel_.get(), cq, rpcmethod_ListenNextJobArrived_, context, request, false, nullptr);
}

::grpc::ClientReader< ::duo::ListenJobChangedResponse>* JobService::Stub::ListenJobChangedRaw(::grpc::ClientContext* context, const ::duo::ListenJobChangedRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::duo::ListenJobChangedResponse>::Create(channel_.get(), rpcmethod_ListenJobChanged_, context, request);
}

void JobService::Stub::async::ListenJobChanged(::grpc::ClientContext* context, const ::duo::ListenJobChangedRequest* request, ::grpc::ClientReadReactor< ::duo::ListenJobChangedResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::duo::ListenJobChangedResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ListenJobChanged_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::duo::ListenJobChangedResponse>* JobService::Stub::AsyncListenJobChangedRaw(::grpc::ClientContext* context, const ::duo::ListenJobChangedRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenJobChangedResponse>::Create(channel_.get(), cq, rpcmethod_ListenJobChanged_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::duo::ListenJobChangedResponse>* JobService::Stub::PrepareAsyncListenJobChangedRaw(::grpc::ClientContext* context, const ::duo::ListenJobChangedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::duo::ListenJobChangedResponse>::Create(channel_.get(), cq, rpcmethod_ListenJobChanged_, context, request, false, nullptr);
}

::grpc::Status JobService::Stub::Ping(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::duo::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::duo::PingRequest, ::duo::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void JobService::Stub::async::Ping(::grpc::ClientContext* context, const ::duo::PingRequest* request, ::duo::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::duo::PingRequest, ::duo::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void JobService::Stub::async::Ping(::grpc::ClientContext* context, const ::duo::PingRequest* request, ::duo::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::duo::PingResponse>* JobService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::duo::PingResponse, ::duo::PingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::duo::PingResponse>* JobService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

JobService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobService::Service, ::duo::GetJobRequest, ::duo::GetJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::GetJobRequest* req,
             ::duo::GetJobResponse* resp) {
               return service->GetJob(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobService::Service, ::duo::GetNextJobRequest, ::duo::GetJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::GetNextJobRequest* req,
             ::duo::GetJobResponse* resp) {
               return service->GetNextJob(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobService::Service, ::duo::GetUnfinishedJobsRequest, ::duo::GetJobsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::GetUnfinishedJobsRequest* req,
             ::duo::GetJobsResponse* resp) {
               return service->GetUnfinishedJobs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobService::Service, ::duo::GetFinishedJobsRequest, ::duo::GetJobsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::GetFinishedJobsRequest* req,
             ::duo::GetJobsResponse* resp) {
               return service->GetFinishedJobs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobService::Service, ::duo::CreateJobRequest, ::duo::CreateJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::CreateJobRequest* req,
             ::duo::CreateJobResponse* resp) {
               return service->CreateJob(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobService::Service, ::duo::DeleteFinishedJobsRequest, ::duo::JobDeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::DeleteFinishedJobsRequest* req,
             ::duo::JobDeleteResponse* resp) {
               return service->DeleteFinishedJobs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobService::Service, ::duo::UpdateJobRequest, ::duo::UpdateJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::UpdateJobRequest* req,
             ::duo::UpdateJobResponse* resp) {
               return service->UpdateJob(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[7],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< JobService::Service, ::duo::ListenNextJobArrivedRequest, ::duo::ListenNextJobArrivedResponse>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::ListenNextJobArrivedRequest* req,
             ::grpc::ServerWriter<::duo::ListenNextJobArrivedResponse>* writer) {
               return service->ListenNextJobArrived(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[8],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< JobService::Service, ::duo::ListenJobChangedRequest, ::duo::ListenJobChangedResponse>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::ListenJobChangedRequest* req,
             ::grpc::ServerWriter<::duo::ListenJobChangedResponse>* writer) {
               return service->ListenJobChanged(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobService::Service, ::duo::PingRequest, ::duo::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::duo::PingRequest* req,
             ::duo::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
}

JobService::Service::~Service() {
}

::grpc::Status JobService::Service::GetJob(::grpc::ServerContext* context, const ::duo::GetJobRequest* request, ::duo::GetJobResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobService::Service::GetNextJob(::grpc::ServerContext* context, const ::duo::GetNextJobRequest* request, ::duo::GetJobResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobService::Service::GetUnfinishedJobs(::grpc::ServerContext* context, const ::duo::GetUnfinishedJobsRequest* request, ::duo::GetJobsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobService::Service::GetFinishedJobs(::grpc::ServerContext* context, const ::duo::GetFinishedJobsRequest* request, ::duo::GetJobsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobService::Service::CreateJob(::grpc::ServerContext* context, const ::duo::CreateJobRequest* request, ::duo::CreateJobResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobService::Service::DeleteFinishedJobs(::grpc::ServerContext* context, const ::duo::DeleteFinishedJobsRequest* request, ::duo::JobDeleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobService::Service::UpdateJob(::grpc::ServerContext* context, const ::duo::UpdateJobRequest* request, ::duo::UpdateJobResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobService::Service::ListenNextJobArrived(::grpc::ServerContext* context, const ::duo::ListenNextJobArrivedRequest* request, ::grpc::ServerWriter< ::duo::ListenNextJobArrivedResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobService::Service::ListenJobChanged(::grpc::ServerContext* context, const ::duo::ListenJobChangedRequest* request, ::grpc::ServerWriter< ::duo::ListenJobChangedResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobService::Service::Ping(::grpc::ServerContext* context, const ::duo::PingRequest* request, ::duo::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace duo

