// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: duo/duo.proto

#include "duo/duo.pb.h"
#include "duo/duo.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace duo {

class MockShadowServiceStub : public ShadowService::StubInterface {
 public:
  MOCK_METHOD3(GetThingList, ::grpc::Status(::grpc::ClientContext* context, const ::duo::GetThingListRequest& request, ::duo::GetThingListResponse* response));
  MOCK_METHOD3(AsyncGetThingListRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetThingListResponse>*(::grpc::ClientContext* context, const ::duo::GetThingListRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetThingListRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetThingListResponse>*(::grpc::ClientContext* context, const ::duo::GetThingListRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetReport, ::grpc::Status(::grpc::ClientContext* context, const ::duo::GetReportRequest& request, ::duo::GetResponse* response));
  MOCK_METHOD3(AsyncGetReportRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetResponse>*(::grpc::ClientContext* context, const ::duo::GetReportRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetReportRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetResponse>*(::grpc::ClientContext* context, const ::duo::GetReportRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetDesire, ::grpc::Status(::grpc::ClientContext* context, const ::duo::GetDesireRequest& request, ::duo::GetResponse* response));
  MOCK_METHOD3(AsyncGetDesireRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetResponse>*(::grpc::ClientContext* context, const ::duo::GetDesireRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetDesireRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetResponse>*(::grpc::ClientContext* context, const ::duo::GetDesireRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetDelta, ::grpc::Status(::grpc::ClientContext* context, const ::duo::GetDeltaRequest& request, ::duo::GetResponse* response));
  MOCK_METHOD3(AsyncGetDeltaRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetResponse>*(::grpc::ClientContext* context, const ::duo::GetDeltaRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetDeltaRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetResponse>*(::grpc::ClientContext* context, const ::duo::GetDeltaRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PatchReport, ::grpc::Status(::grpc::ClientContext* context, const ::duo::PatchReportRequest& request, ::duo::PatchResponse* response));
  MOCK_METHOD3(AsyncPatchReportRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::PatchResponse>*(::grpc::ClientContext* context, const ::duo::PatchReportRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncPatchReportRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::PatchResponse>*(::grpc::ClientContext* context, const ::duo::PatchReportRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PatchDesire, ::grpc::Status(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::duo::PatchResponse* response));
  MOCK_METHOD3(AsyncPatchDesireRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::PatchResponse>*(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncPatchDesireRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::PatchResponse>*(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(Delete, ::grpc::Status(::grpc::ClientContext* context, const ::duo::DeleteRequest& request, ::duo::DeleteResponse* response));
  MOCK_METHOD3(AsyncDeleteRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::DeleteResponse>*(::grpc::ClientContext* context, const ::duo::DeleteRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncDeleteRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::DeleteResponse>*(::grpc::ClientContext* context, const ::duo::DeleteRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(UploadRaw, ::grpc::ClientWriterInterface< ::duo::UploadRequest>*(::grpc::ClientContext* context, ::duo::UploadResponse* response));
  MOCK_METHOD4(AsyncUploadRaw, ::grpc::ClientAsyncWriterInterface< ::duo::UploadRequest>*(::grpc::ClientContext* context, ::duo::UploadResponse* response, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncUploadRaw, ::grpc::ClientAsyncWriterInterface< ::duo::UploadRequest>*(::grpc::ClientContext* context, ::duo::UploadResponse* response, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(PatchDesireAndWaitRaw, ::grpc::ClientReaderInterface< ::duo::PatchAndWaitResponse>*(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request));
  MOCK_METHOD4(AsyncPatchDesireAndWaitRaw, ::grpc::ClientAsyncReaderInterface< ::duo::PatchAndWaitResponse>*(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncPatchDesireAndWaitRaw, ::grpc::ClientAsyncReaderInterface< ::duo::PatchAndWaitResponse>*(::grpc::ClientContext* context, const ::duo::PatchDesireRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(ListenReportRaw, ::grpc::ClientReaderInterface< ::duo::ListenResponse>*(::grpc::ClientContext* context, const ::duo::ListenReportRequest& request));
  MOCK_METHOD4(AsyncListenReportRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenResponse>*(::grpc::ClientContext* context, const ::duo::ListenReportRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncListenReportRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenResponse>*(::grpc::ClientContext* context, const ::duo::ListenReportRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(ListenDesireRaw, ::grpc::ClientReaderInterface< ::duo::ListenResponse>*(::grpc::ClientContext* context, const ::duo::ListenDesireRequest& request));
  MOCK_METHOD4(AsyncListenDesireRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenResponse>*(::grpc::ClientContext* context, const ::duo::ListenDesireRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncListenDesireRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenResponse>*(::grpc::ClientContext* context, const ::duo::ListenDesireRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(ListenDeltaRaw, ::grpc::ClientReaderInterface< ::duo::ListenResponse>*(::grpc::ClientContext* context, const ::duo::ListenDeltaRequest& request));
  MOCK_METHOD4(AsyncListenDeltaRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenResponse>*(::grpc::ClientContext* context, const ::duo::ListenDeltaRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncListenDeltaRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenResponse>*(::grpc::ClientContext* context, const ::duo::ListenDeltaRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(Ping, ::grpc::Status(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::duo::PingResponse* response));
  MOCK_METHOD3(AsyncPingRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::PingResponse>*(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncPingRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::PingResponse>*(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::grpc::CompletionQueue* cq));
};

class MockJobServiceStub : public JobService::StubInterface {
 public:
  MOCK_METHOD3(GetJob, ::grpc::Status(::grpc::ClientContext* context, const ::duo::GetJobRequest& request, ::duo::GetJobResponse* response));
  MOCK_METHOD3(AsyncGetJobRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetJobResponse>*(::grpc::ClientContext* context, const ::duo::GetJobRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetJobRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetJobResponse>*(::grpc::ClientContext* context, const ::duo::GetJobRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetNextJob, ::grpc::Status(::grpc::ClientContext* context, const ::duo::GetNextJobRequest& request, ::duo::GetJobResponse* response));
  MOCK_METHOD3(AsyncGetNextJobRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetJobResponse>*(::grpc::ClientContext* context, const ::duo::GetNextJobRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetNextJobRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetJobResponse>*(::grpc::ClientContext* context, const ::duo::GetNextJobRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetUnfinishedJobs, ::grpc::Status(::grpc::ClientContext* context, const ::duo::GetUnfinishedJobsRequest& request, ::duo::GetJobsResponse* response));
  MOCK_METHOD3(AsyncGetUnfinishedJobsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetJobsResponse>*(::grpc::ClientContext* context, const ::duo::GetUnfinishedJobsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetUnfinishedJobsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetJobsResponse>*(::grpc::ClientContext* context, const ::duo::GetUnfinishedJobsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetFinishedJobs, ::grpc::Status(::grpc::ClientContext* context, const ::duo::GetFinishedJobsRequest& request, ::duo::GetJobsResponse* response));
  MOCK_METHOD3(AsyncGetFinishedJobsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetJobsResponse>*(::grpc::ClientContext* context, const ::duo::GetFinishedJobsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetFinishedJobsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::GetJobsResponse>*(::grpc::ClientContext* context, const ::duo::GetFinishedJobsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(CreateJob, ::grpc::Status(::grpc::ClientContext* context, const ::duo::CreateJobRequest& request, ::duo::CreateJobResponse* response));
  MOCK_METHOD3(AsyncCreateJobRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::CreateJobResponse>*(::grpc::ClientContext* context, const ::duo::CreateJobRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncCreateJobRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::CreateJobResponse>*(::grpc::ClientContext* context, const ::duo::CreateJobRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(DeleteFinishedJobs, ::grpc::Status(::grpc::ClientContext* context, const ::duo::DeleteFinishedJobsRequest& request, ::duo::JobDeleteResponse* response));
  MOCK_METHOD3(AsyncDeleteFinishedJobsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::JobDeleteResponse>*(::grpc::ClientContext* context, const ::duo::DeleteFinishedJobsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncDeleteFinishedJobsRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::JobDeleteResponse>*(::grpc::ClientContext* context, const ::duo::DeleteFinishedJobsRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(UpdateJob, ::grpc::Status(::grpc::ClientContext* context, const ::duo::UpdateJobRequest& request, ::duo::UpdateJobResponse* response));
  MOCK_METHOD3(AsyncUpdateJobRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::UpdateJobResponse>*(::grpc::ClientContext* context, const ::duo::UpdateJobRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncUpdateJobRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::UpdateJobResponse>*(::grpc::ClientContext* context, const ::duo::UpdateJobRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(ListenNextJobArrivedRaw, ::grpc::ClientReaderInterface< ::duo::ListenNextJobArrivedResponse>*(::grpc::ClientContext* context, const ::duo::ListenNextJobArrivedRequest& request));
  MOCK_METHOD4(AsyncListenNextJobArrivedRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenNextJobArrivedResponse>*(::grpc::ClientContext* context, const ::duo::ListenNextJobArrivedRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncListenNextJobArrivedRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenNextJobArrivedResponse>*(::grpc::ClientContext* context, const ::duo::ListenNextJobArrivedRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(ListenJobChangedRaw, ::grpc::ClientReaderInterface< ::duo::ListenJobChangedResponse>*(::grpc::ClientContext* context, const ::duo::ListenJobChangedRequest& request));
  MOCK_METHOD4(AsyncListenJobChangedRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenJobChangedResponse>*(::grpc::ClientContext* context, const ::duo::ListenJobChangedRequest& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncListenJobChangedRaw, ::grpc::ClientAsyncReaderInterface< ::duo::ListenJobChangedResponse>*(::grpc::ClientContext* context, const ::duo::ListenJobChangedRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(Ping, ::grpc::Status(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::duo::PingResponse* response));
  MOCK_METHOD3(AsyncPingRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::PingResponse>*(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncPingRaw, ::grpc::ClientAsyncResponseReaderInterface< ::duo::PingResponse>*(::grpc::ClientContext* context, const ::duo::PingRequest& request, ::grpc::CompletionQueue* cq));
};

} // namespace duo

