// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: duo/types.proto

#include "duo/types.pb.h"
#include "duo/types.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace duo {

} // namespace duo

